* *Tasks*
** DONE [#A] Take a look at Brett's document
	[[message://%3c000000000000a31d91058568e25b@google.com%3E][complex cases - Invitation to collaborate]]
** DONE [#A] Complex cases book meeting tomorrow?
** DONE [#A] Look at the MI case that Brett created and start determining topics to focus on. 
SCHEDULED: <2019-04-29 Mon>
	[[message://%3cCAG32-bCe3aZXGQE61Wdo3SmDpGNWmmf3bqntzjTB9DBgGJLAFw@mail.gmail.com%3E][Notes from Last Book Meeting]]
** ON RADAR Go through this concept map for the book
	[[message://%3c7YHQ2_PvHojrfBdPOQzmFg.0@notifications.google.com%3E][Complex cases boo... - My original, I have ppt that I copied...]]
** TODO Scott Stern symptom to diagnosis 
** DONE The Agony and the Ecstasy: A Biographical Novel of Michelangelo: Irving Stone: 9780451171351: Amazon.com: Books
https://www.amazon.com/Agony-Ecstasy-Biographical-Novel-Michelangelo/dp/0451171357

* *Ticklers*
* *Meetings*
** Initial planning meeting <2019-03-22 Fri>

Hi All,
 
Brett, Paola, Tom, and I met to discuss first steps on this book. Here is the to do list and goals right now:
 
We are looking to target late M2 (pre-USMLE Step 1) through year 1 of residency.
Goal: Each chapter is a very complex cases with significant complications used to work through different disciplines and clinical reasoning.
Maureen to contact Legal
Brett, Maureen, Paola to contact designers
Maureen to contact editor/writer
Brett and Paola to get case list
Brett to develop outline of skeleton of chapter and share with group at next meeting
 
 
At the next meeting:
Brett and Paola to share case list and why
Update from Legal
Brett to share outline of a chapter/structure of a chapter
Determine process for first draft of table of contents
Writing assignments
 
Here are my notes from the meeting: https://docs.google.com/document/d/1t8SbZREeqKQ3XNQzEcJM5AH2ey_10vUGFUy6zHlCtmc/edit?usp=sharing
 
Maureen
** Book Meeting <2019-04-05 Fri 10:00-11:00>

** Book meeting <2019-05-03 Fri 12:00-13:00>
:PROPERTIES:
:SYNCID:   05978528-7A94-4593-A1D5-0E4CCBFC6161
:ID:       18853F3A-109F-442F-BA98-6D918CF10C2C
:END:
	[[message://%3cCAG32-bCe3aZXGQE61Wdo3SmDpGNWmmf3bqntzjTB9DBgGJLAFw@mail.gmail.com%3E][Notes from Last Book Meeting]]

*** I simply edited the document with comments.  This was easier, I think.  See what Brett says.
*** Should I acutally start writing exercises?
*** Maureen took notes. I'll add them when she sends them.  Bottom line for me:
**** start writing
**** all narrative, no problems
**** communicate with Anne on the pathophys and make sure she is on board with whatever youwrite.
**** We meet again in two weeks.  Get something done before then.
*** [[https://docs.google.com/document/d/10nTOOkIRCogSi0SBx5qbGj0Tue0u1jGoYS_8C3VEfOo/edit][Meeting Minutes 5/3/2019 - Google Docs]]
:PROPERTIES:
:SYNCID:   7E088786-01A6-4F42-8474-3BA9A6899041
:ID:       CA93736B-CEF4-4F3B-8A30-40E195A2AEE7
:END:

Meeting Minutes 5/3/2019

Discussion on the overall structure of a chapter
The chapter should read much like a case whenever possible beginning with a brief HPI that includes pertinent positives and negatives including a mini physical exam that only contains the relevant findings. 
Differential Diagnosis Table: Following the HPI there will be a Complaint based differential diagnosis table that is organized according to priority based on semantic qualifiers. EBM may be useful here in discussing your priority ranking of differential. 
Testing: The next section will begin with which tests to order and brief overview of why you order them then moving into what the test tells you about the disease from a foundational science perspective (including path, immuno, micro, EBM, and physio). 
Test Results: Give most likely test results - explain them in the context of pathophysiology and foundational science as related to the condition. Mini summary and treatment, explain the pharm.
FOLLOW-UP Visit: Each case is complex, so the patient will return with a new/worsening complaint that then will explore a different path. The chapter format essentially starts over with a DDx table, testing, results, and treatment with foundaitonal science woven in. This is also where call out boxes for “switcher-roo” may come in. 
At the end of the chapter, once all follow-ups are finished a clinical summary should be given as well as a summary of the foundational sciences. 

2. Resources:
	We may want to check out Critical Questions: Symptom to Diagnosis  by Scott Stern as a resource in writing chapters. 

3. Next Steps:
	Paola: Diabetes Case
Brett: MI case
Anne and Keith: Batch the case list and identify areas to integrate diagnoses, EBM, and medical ethics in order to eliminate redundancies. 
Maureen: Create Refworks for resource list and template, add content on RF criteria and immune to the MI case as well as vegatitve growth. 
Tom: begin adding physio content in cases
* *Notes*
** [[https://drive.google.com/drive/folders/1ObKgKyCRqcfPVr9p05I9u36RmKd-yUZB][Complex Cases Folder - Google Drive]]
** [[/Users/tshanno/Library/Mobile Documents/com~apple~CloudDocs/PowerPoint/Book PPT 2019-05-03.pptx][Book PowerPoint 2019-05-03]]
** [[https://en.wikipedia.org/wiki/Dressler_syndrome][Dressler syndrome]]


