* *Notes*
** [[/Users/tshanno/Library/Mobile Documents/com~apple~Preview/Documents/Easter 2019 Southwest Airlines - Purchase Confirmation.pdf][Easter Plane Reservation]]
** Easter Sunday:
:PROPERTIES:
:SYNCID:   EABDD297-0FB6-4062-9170-1DCE43CBE456
:ID:       9073FDAC-E137-4ECD-B81D-F66B0C2BC5E4
:END:
Entered on [2019-04-21 Sun 09:01]
*** Go to a different mass next year unless they have changed the times.  See if you can find something earlier.  People were standing at 7:30 and I had to par at the high school.    See if you can find an earlier mass somewhere.
*** Mom cancelled the Easter egg hunt.  Greg and his family weren't going to make it until late and they decided it wasn't worth it.
*** Melissa announced that she was pregnant last night.  We don't know if they're getting married.  She didn't look like she was feeling well.  Hopefully all is OK.  

She had already told me and Mom and Dad.  Obviously the immediate family knew.  Even given that, I didn't think there was a great deal of surprise and I wondered how many other people knew.

** Rapid Rewards 626135370
:PROPERTIES:
:SYNCID:   85C1BF2B-716F-48CA-AF40-4914151ED318
:ID:       FC72327E-A473-4BD3-B292-94BE5FCA2B81
:END:
* *Tasks*
** DONE [#A] Send Dad plane reservation information for Easter
