* Tasks
** TODO Course Director's Meeting; Location: OMSP 403B~ Large Conference room 407 <2019-09-05 Thu 12:00-13:00>
** TODO Tom Shannon - Dan Bare; Location: 1750 W Harrison St. <2019-09-05 Thu 09:45-10:15>
** TODO Email DDs and ask them to send you slides for debrief
** TODO Send out invite to formative review

** TODO [[message://%3c8E19A0FC-741C-4299-ABDD-BE722A04583E@rush.edu%3E][Bare Extension]]


Hi, Xun.

Dan talked to me this morning and he said you’d like a one month extension on his services.  He was supposed to go back to work with me in mid-September.  

I would therefore propose that we go ahead and have him work for you to the end of October.  This adds 6 weeks - two weeks of vacation that Dan plans to take during that time plus an extra 4 weeks of work.

That would leave us with this:

Xun: present - October 31
Tom:  November 1 - January 31
Continuing to alternate every two months after that.

Is that acceptable?

Thanks,
Tom S.
** TODO Be sure to tell Janice that you altered the plan of study for Tetralogy of Fallot and MI 1
