* Tasks
** TODO [[~/Library/Mobile Documents/com~apple~CloudDocs/Excel/Videos moved from Angela Solic account to RMC Integrated account 2018-01-03.xlsx][Videos moved from Angela Solic account to RMC Integrated account 2018-01-03.xlsx]]

** TODO [[message://%3c90E26D71-F8DA-46AA-B80A-0D86E985F42E@me.com%3E][ Emacs Keybindings for Mac OS X | Irreal]]

** TODO [[message://%3c05455C2B-F5A4-4DF6-B690-C89CDEC6124A@me.com%3E][CBFF QR Codes on the Command-Line | Jonathan Palardy's Blog]]

** TODO Do your own scouting for Dolphins draft: Here are top prospects to watch this weekend - South Florida Sun-Sentinel
https://www.sun-sentinel.com/sports/miami-dolphins/fl-sp-dolphins-draft-scouting-games-20191010-z3t4sd4d6fb6tmnfsfdkvplkuy-story.html

Oklahoma vs. Texas

When: Saturday, noon

How to watch: Fox (Chs. 7, 29)

Players to watch: Defensive lineman Neville Gallimore (No. 90, Oklahoma), quarterback Jalen Hurts (No. 1,
Oklahoma), wide receiver Collin Johnson (jersey No. 9, Texas), wide receiver CeeDee Lamb (No. 2, Oklahoma) and
linebacker Kenneth Murray (No. 9, Oklahoma)

Penn St. at Iowa 

When: Saturday, 7:30 p.m.

How to watch: ABC (Chs. 10, 25)

Latest Miami Dolphins

* Dolphins welcome back veteran to injury-ravaged receiver unit ahead of Redskins game 
Dolphins welcome back veteran to injury-ravaged receiver unit ahead of Redskins game
* Here’s what a Dolphins win against Redskins could mean for Miami — this season 
Here’s what a Dolphins win against Redskins could mean for Miami — this season
* The NFL says these were the greatest Dolphins games of all time 
The NFL says these were the greatest Dolphins games of all time

Players to watch: Edge rusher A.J. Epenesa (jersey No. 94, Iowa), edge rusher Yetur Gross-Matos (No. 99, Penn
State) and offensive tackle Tristan Wirfs (No. 74, Iowa)

Florida at LSU

When: Saturday, 8 p.m.

How to watch: ESPN

Players to watch: Quarterback Joe Burrow (jersey No. 9, LSU), safety Grant Delpit (No. 7, LSU), cornerback
Kristian Fulton (No. 1, LSU), edge rusher Jonathan Greenard (No. 58, Florida), cornerback CJ Henderson (No. 1,
Florida) and defensive lineman Tedarrell Slaton (No. 56, Florida)
