* Tasks
** TODO Check to make sure your assessment is still on autopay [[message://%3cBYAPR05MB42006781CA1AB7A5BF466055EA680@BYAPR05MB4200.namprd05.prod.outlook.com%3E][899 S PLYMOUTH COURT STATEMENT OF ACCOUNT]]
** TODO Write up a procedure for longitudinal course review
* TODO James Parker 1
:LOGBOOK:
- Note taken on [2019-10-24 Thu 06:58] \\
  Set up for TBC students
  
  | CE | Group | Eval Code | 
  | Christine | 7 | ev6759 |
  | Meeta      | 8 | ev4510 |
:END:
** TODO FU Angela Solic [[message://%3cd71b336a1cdb46d980b8d4f161f0ccd3@RUPW-EXCHMAIL02.rush.edu%3E][FW: Video recording]]
** TODO FU Angela Solic [[message://%3cd71b336a1cdb46d980b8d4f161f0ccd3@RUPW-EXCHMAIL02.rush.edu%3E][FW: Video recording]]
* TODO ‘You can’t panic’: Matt Nagy still catching his breath after the Bears’ jarring loss to the Packers - Chicago Tribune
[2019-09-07 Sat 02:14]
https://www.chicagotribune.com/sports/bears/ct-bears-matt-nagy-mitch-trubisky-20190906-bshie4reijg3jhequphhfsxjwm-story.html

On what he learned about his own play-calling in the season opener

It wasn’t good enough. I told the players that. I told them that last night in the locker room. It starts with me. I need to be better and I will be better and I’m going to demand that from myself, from our coaches and from our players. I think good coaches figure out the why part. They don’t just get all angry and upset and start pointing fingers or being frustrated. Last night? That was tough. And I’m not talking about right after the game. I’m talking about the whole night and even this morning. You still feel it. But I have this competitiveness in me that I’m not going to let that take away from how I’m going to attack this next week. I’m going to use this to make me a better coach and we’re going to use it as a team. I need to be better, there’s no doubt about it.

That’s a fair assessment. It’s easy to forget that Nagy is a young coach.
