* Tasks

** TODO FU:  Jay [[message://%3c1571395242605.21960@rush.edu%3E][Re: TBC tomorrow]]

** TODO FU:  Danesha [[message://%3ccd2a39cfd08747369178fea4c7d4c2ac@RUDW-EXCHMAIL02.rush.edu%3E][RE: Questions about upcoming sessions]]
Hi.
 
I’m still working on putting Scholar in the new template. I’ll be done soon.
 
I met with Nina yesterday and she doesn’t want student guide for the sessions. So both sessions are just faculty guides.
 
I have the faculty guides for Advocate. He and Scholar were my last two role areas to work on.
 
I’m not sure about that practitioner session. I would need to check.
 
 
Danesha
---- 
So I’m looking ahead to see where we’re at:
 
10/28 Scholar - I see the self-study (thanks) but no faculty or student guide.  Is there nothing of that nature for this session?
10/29 Leader - I see the faculty guide and the self-study.  Shouldn’t there be a student guide?
10/29 Advocate - I see the self-study (again, thanks) but no faculty or student guide.  Is Paul behind getting these materials to you?  Do you need me to prompt him?
11/1 Practitioner:  Intro to the Stethoscope - I don’t see a section on Entrada for this.  Shouldn’t there be one?
 
Thanks,
Tom S.
 

** TODO Get flu shot [[message://%3c8cffe193552f4ca6a699459bc73e8563@RUDWV-EXCHEG001.dmz.rush.edu%3E][2019-2020 Seasonal Influenza Consent Form Submitted Successfully]]


Hi.
 
I’m still working on putting Scholar in the new template. I’ll be done soon.
 
I met with Nina yesterday and she doesn’t want student guide for the sessions. So both sessions are just faculty guides.
 
I have the faculty guides for Advocate. He and Scholar were my last two role areas to work on.
 
I’m not sure about that practitioner session. I would need to check.
 
 
Danesha
 
From: Tom Shannon 
Sent: Friday, October 18, 2019 3:11 AM
To: Danesha Lewis <Danesha_Lewis@rush.edu>
Subject: Questions about upcoming sessions
 
Hi, Danesha.
 
So I’m looking ahead to see where we’re at:
 
10/28 Scholar - I see the self-study (thanks) but no faculty or student guide.  Is there nothing of that nature for this session?
10/29 Leader - I see the faculty guide and the self-study.  Shouldn’t there be a student guide?
10/29 Advocate - I see the self-study (again, thanks) but no faculty or student guide.  Is Paul behind getting these materials to you?  Do you need me to prompt him?
11/1 Practitioner:  Intro to the Stethoscope - I don’t see a section on Entrada for this.  Shouldn’t there be one?
 
Thanks,
Tom S.
** TODO M4s working MI 1
*** Junwei_Li@rush.edu - Paola_Susan@rush.edu
*** Jared_D_Miya@rush.edu - stephen_r_gore@rush.edu
*** Eric_P_Moyer@rush.edu - -ewa_dembowski@rush.edu

** TODO Go through James Parker 2 assessment [[message://%3cB8D9CC3A-9137-4F69-823B-F8347C8B7F2E@rush.edu%3E][Re: RMD 574 James Parker 2 Session Assessment ]]

** TODO FU: Bob [[message://%3c3AF8658A-96B8-4B88-8F1A-5C80350FA37B@rush.edu%3E][Re: 10/22 - Intro to Patient Safety Time Change ]]

** TODO FU: Sabine [[message://%3c026BED5E-DDB3-4BAA-B79A-B480902A086F@rush.edu%3E][Re: Virus and peptide]]

** TODO FU Mike [[message://%3c7978B14F-CACD-4BD0-BC38-5685FF72B0C5@rush.edu%3E][Re: UCC invitation ]]
