* Tasks
** Cameo at M1 Orientation; Location: 540 AAC <2019-08-22 Thu 10:15-10:45>
** Med Ed Research Group; Location: OIME Large Conference Room <2019-08-22 Thu 12:00-13:00>
** Request - RMC Faculty Dinner and Curriculum Prep meeting; Location: AAC 1096 - https://zoom.us/j/153650743 <2019-08-22 Thu 17:00-18:30>
** TODO Make sure there are markers for th ewhite boards for each of the eight groups.
** TODO [[https://www.watchophilia.com/photogallery/bulovas-1940-1949/][Bulova - Vintage Watches 1940s | Watchophilia.com]]
* TODO Column: Matt Nagy is waiting until the season opener for the big reveal of the Bears’ revamped running game. And it should be worth the wait. - Chicago Tribune
[2019-08-23 Fri 02:01]
https://www.chicagotribune.com/sports/bears/ct-bears-running-game-david-montgomery-mike-davis-20190822-sniz4uk4zjejtlnw6yg6jisogy-story.html

The other thing about Howard last season — and the third-down run against the Eagles is a prime example — is he didn’t run with the burst and speed through the hole that he did earlier in his career.

Bears running back Mike Davis, taking a handoff during a training camp practice, should show more burst and pass-catching ability than Jordan Howard did last season.
Bears running back Mike Davis, taking a handoff during a training camp practice, should show more burst and pass-catching ability than Jordan Howard did last season. (Jose M. Osorio / Chicago Tribune)
A running back’s timed speed in the 40-yard dash isn’t very important. Montgomery and Davis should be an upgrade over Howard when it comes to their burst — the time it takes them to get from zero to 10 yards. When daylight starts to close fast, a running back must navigate the hole with speed. When he does that, he’s at the second level and you’re looking at a chunk gain.

Knee surgery
