* *Tasks*
* *Ticklers*
* *Notes*
** [[~/Library/Mobile Documents/com~apple~Preview/Documents/IACUC Investigator User Guide RUSH_V1.pdf][IACUC Investigator User Guide RUSH_V1.pdf]]
** [[~/Library/Mobile Documents/com~apple~Preview/Documents/LARS PI User Guide_RUSH V1 2019-06-28.pdf][LARS PI User Guide_RUSH V1 2019-06-28.pdf]]

* *Meetings*
** eRAM Training Session
Scheduled: Jun 28, 2019 at 9:00 AM to 11:45 AM
*** [[message://%3c0100016b4bdda5b4-9f93318a-f166-42fe-8b7e-d71e9026bfac-000000@email.amazonses.com%3E][Registration Confirmation - eRAM Principal Investigator and Staff Training]]
Notes: 
Please bring your portable device (laptop or iPad) to help facilitate the interactive training. 

Please plan to arive with enough time to sign attendance sheet roster and be seated by 9:00 AM. It is your personal responbility to cancel your enrollment for this course if you find you cannot attend. Failure to do so will result in a no-show on your record. Thank you for your cooperation. 

If you have any questions, or find you need to change your class registration, please email Danita_M_Schaal@rush.edu so we can ensure your needs are met. 

