* *Tasks*
* *Ticklers*
* *Notes* 
**** Lots of video making
:PROPERTIES:
:SYNCID:   F77FC921-B97D-4CE5-A294-8134DA8F58EC
:ID:       4E26DBBC-7F58-4EE7-B810-362724D9002B
:END:
***** Re-recorded part 2 of osteoporosis physiology review and uploaded to youtube
***** Cut the first slide (office hours, etc... had changed) from osteoporosis part 1 and uploaded to youtube.
***** Cut the first slide from muscular dystrophy part 1 and re-uploaded
***** Cut the first slide from myasthenia gravis part 1 and re-uploaded
***** Uploaded all corrected PowerPoints and video links to Entrada.  Muscular dystrophys stuff is scheduled for release Thursday after the session.  All else immediately released.
***** Also added the second part of the R1 Introduction to the Respiratory System, exported from iMovie, and uploaded to youtube.  this is a new, longer video with an "Intermission" slide half way through rather than two seperate videos.
Entered on [2019-04-16 Tue 11:40]
  
  [[file:~/Library/Mobile%20Documents/com~apple~CloudDocs/Emacs/Org/notes/video%20links%20for%20curriculum.org::*Muscular%20Dystrophy%20Physiology%20Review%20Part%201%202019-04-16:%20https://youtu.be/u-KdQDe1ZMc%20(12:38)][Muscular Dystrophy Physiology Review Part 1 2019-04-16: https://youtu.be/u-KdQDe1ZMc (12:38)]]

* DONE [#A] Resting potential, action potential, synapses due 3/19
* DONE [#A] [[https://docs.google.com/document/d/1mPqlTdxTcDPSwIdMdd-Lex4_8xZceNxWif2H6WTbIro/edit][Look over activity 2]]
* DONE [#A] [[message://%3cCB754447-D1CD-4E0A-9899-6D58955EAFD8@rush.edu%3E][Look at activity and comment]]
