Dolphins on offense
Brock Osweiler 8 Not particularly accurate.
David Fales 9  Threw high and in front of Owusu then behind 81 for an INT.  Behind 82 on 4th and 4 later in the quarter though it was har dto tell if it was supposed to be a back shoulder throw.
Bryce Petty 14
Ryan Tannehil 17 looked really sharp.  Good accuracy.  Made the reads.  Threw with authority.

Kallen Ballage 33

Daniel Kilgore 67 - looks good.  Appear to be able to run block pretty well.  Did have a tough time with one block on a screen play but it looked like a pretty good play by the defender.
Laremy Tunsil 78

Leonte Carroo 88
Mike Gesicki 86
Francis Owusu 82
Devante Parker 11
Albery Wilson 15


Dolphins on Defense
Jerome Baker 55
Raekwon McMillan 52 - got blocked solidly out of the hole on the McCaffry touchdown.  He's got a tough time taking on blocks but he has good range which he frequenltly shoed.  It looked like he failed to pick up TE Ian Thomas on the TD near the end of the second half.

Davon Godchaux 56
Charles Harris 90
Jordan Phillips 97
Vincent Taylor 96 - struggling to hold against the run.
53 got blocked out of the play on the first carolina td McCaffry

Minka Fitzpatrick 29
Bobby McCain 28
Cordrea Tankersly 30 Got burned on a long pass in the fourth quarter
Torry McTyer 24


Panthers playing off defense.  Dolphins mostly short passes.  Albert Wilson involved early.  Tannehill looks OK.

Sanders kicked a 42 yarder.  Also a short one late in the first quarter (28 yards?).  Greg Joseph with a 54 yarder in teh second.  Danders 32 yarder 3rd q.

Xavien HOward with a nice inerception in the first quarter.  39 yard return to the 9.  PI in the second gave Carolina a first down.

Holding Tunsil and Davis

Delay of game on third and goal from the 9 in first quarter

Robert Quinn with two sacks.

Drew MOrgan muffed a punt at the bginning of the 2nd quarter.

Miami showed a lot of blitzes.  They weren't particularly effective.

INT MAurice Smith 3rd quarter.  Fales take over at teh 10.  He made a nice pass to the back of the end zone but Carroo couldn't get a second foot down.  A better WR might have gotten it done.






* Stock up:

** Ryan Tannehill looked very sharp in Just short of 2 quarters worth of work.  He was 14 of 17 for 100 yards as he dropped back, read the field and delivered the ball reasonably accurately to the open receiver.  He showed no ill effects coming off of a torn ACL in 2017 and his passer rating for the night was a solid 91.2.  Tannehill wasn't asked to do much in that the Dolphins stuck to the short passing game.  But there were virtually no negatives when looking at what he did and his performance was encouraging.

** Robert Quinn, acquired in the offseson from Los Angeles for a fourth round pick made Executive Vice-President of Footabll Operations Mike Tannenbaum and General Manager Chris Greer look good as he showed both quickness and power while rushing off of the edge.  Quinn hasn't been dominant for a couple years but certainly looked like he will be a handful for any offensive tackle in the league one-on-one if he keeps playing like he did against the Panthers.  Overall the Dolphins pass rush was solid and Quinn was a big part of the effort.

** Xavien Howard got an interception on a pass where Cam Newton evidently didn't see him lurking on the left side of the defense.  He returned the ball 34 yards.  Howard also contributed to the rash of penalties by committing a pass interference so his night wasn't perfect.  But his coverage was tight and he looked like he's going to be the kind of asset the Dolphins thought he could be when they drafted him in the second round in 2016.

** Daniel Kilgore.  The offensive line on the whole didn't have a great night but Kilgore was solid in the middle.  He was particularly effective blocking in the running game and held his own in pass protection.  He did have one minor breakdown on a screen pass near the end of the first half but it was a difficult block with the defensive tackle making a good read after shading to the play side of the center.  Miami's situation at right guard and both tackles can be a bit unsteady at times.  Kilgore's presence could help stabilize the situation.

* Stock Down

** Raekwon McMillan is effectively a rookie and though he was improved over his debut performance last week, he sill looks like one as he was vary incosistent on the night.  McMillan shows excellent range and he frequently makes good, quick reads that get him in position to make plays from sideline to sideline.  You can see why the Dolphins liked him when they drafted him in the second round in 2017 before an injury derailed his season.  But McMillan had trouble taking on and getting off of blocks and was solidly sealed out of the hole on the Christian McCaffrey's 71 yard touchdown run in the first quarter.  It also appeared that he failed to pick up TE Ian Thomas in coverage on a 27 yard touchdown pass near the end of the first half.

** David Fales had a bad night as he competes with Brock Osweiler for the back up quarterback job.  Osweiler (10 of 13 passing for 68 yards) wasn't great by any stretch and could improve his ball placement.  But it was nothing compared to Fales's struggles with accuracy.  Fales was only 1 of 6 for 1 yard.  He was high and in front of an open Francis Owusu on a pass in the fourth quarter, then immediately followed it up by throwing behind Drew Morgan for an interception.

** Dolphins defensive tackles.  Akeem Spence, free agent from Detroit, got blocked completely out of the play on McCaffrey's touchdown.  It wasn't an isolated to Spence.   Vincent Taylor and Cameron Malveaux didn't do a very good job of taking advantage of the absence of William Hayes (hamstring) as they were getting pushed around like children's toys.  For the most part all of the defensive tackles as a whole were mauled at the line of scrimmage.  This was bad news for the Dolphins run defense.  The Panthers ran the ball 31 times for 226 yards including 10 times for 113 yards in the first half when the Dolphins starteres were playing most of the time.

** Dolphins team discipline. The Dolphins were on 3 of 12 on third downs and this was largely (though not entirely) due to some bad penalites.  Its only the seond preseason game and sloppy performances aren't uncommon.  But the Dolphins were one of the most penalized teams in the league last year and what makes this game disturbing is that the team has been working on resolving the issue in camp.  Whatever they are doing isn't have an apparent effect.  The Dolphins had 8 penalties for 69 yards on teh night including 4 for 46 yards in the first half.  Howard has his pass interference, right guard Jesse Davis and left tackle Laremy Tunsil both had holding calls and there was a delay of game at the Carolina 9 yard line.  This needs to get cleaned up.

* Other Observations

** There was no apparent advantage gained either way in the kicker competition.  DOlphins seventh round pick Jason Sanders kicked three field goals from 42, 28 and 32 yards.  But undrafted free agent Greg Joseph had the long of the night with his 54 yard field goal in the second quarter.

** The Panthers starters spent the first half playing off coverage and the Dolphins took advantge of what was given to them by going predominantly to th short passing game.  Tannehill averaged only 5.9 yards per pass and didn't throw the ball deep.  They're going to have to execute very well and very consistenlty in the passing game if this tranlates to the regular season.

** The Dolphins showed a surprising amount of their blitz packages.  Most defenses keep their schemes bland during the preseason (as Carolina did) but the Dolphins brought guys from everywhere.  This was notable only in that it wasn't particularly effective.  Cam Newton got the ball out quickly and though the Dolphins did do a good job of generating pressure on him, it didn't come from the blitz.  If this is going to be a big part of the Dolphins defensive game plan this year it needs to get better.
