* Ten Post-Draft Dolphins Thoughts
\begin{enumerate}
\item The Dolphins were very pleased with their first round acquisition, Minka Fitzpatrick, and rightfully so.

  “I didn’t expect Minkah to be there, to be honest with you, for the first pick,” \href{http://www.sun-sentinel.com/sports/miami-dolphins/fl-sp-dolphins-draft-20180428-story.html}{general manager Chris Grier said.}  ”For me, he was probably — however you put it — one of the top five or six players in this draft. As we got calls after the pick, other teams kept calling us telling us, ‘He was in our top five players in the draft.’ For us, the value at that point was surprising that he was there.”

  There were really only three no-brainer picks in this draft:  running back Saquon Barkley, defensive end Bradly Chubb and offensive guard Quenton Nelson.  All went very early.

  Below those three, you could make a case for any of the top prospects remaing going anywhere down to the roughly the 15th pick.  But of that remaining group, Fitzpatrick had easily the highest floor.

  The pre-draft criticism that Fitzpatrick didn't have a positon was a bunch of hooey.  Since when is being versatile considered to be a disadvantage?  Fitzpatrick could play safety or cornerback and could play either one well.  He has the range and coverage skills to be an excellent free safety and could be a valuable chess piece for defensive coordinator Matt Burke.
  
\item  On the down side, the blame for needing to draft a safety after previously addressing the position last year lies squarely on the shoulders of executive vice president of football operations Mike Tannenbaum.  Tannenbaum has a bad habit of being enamoured with ``name'' players and he did it again in this situation.  He jumped at the chance to acquire T.J. McDonald from the Rams without properly evaluating his fit beside All-Pro Rashad Jones.  Both should be strong safties and the two didn't work well together last year.

  Tannenbaum has to stop chasing names and has to give more thought to how both age and fit determine whether a player is right for the Dolphins roster.
  
\item Mike Gesicki and Durhame Graham were also excellent fits for the Dolphins and a good value where they drafted them, especially Gesicki who could have gone in the first round.  Miami lost tight ends Julius Thomas and Anthony Fasano and Dion SImms the year before last.

  This was a position of need and stocking young players who both a guy who could catch the ball in Gesicki and block in Graham was a necessary step to refilling that spot on the roster.  Gesicki could contribute right away.
  \item New running back Kalen Ballage \href{http://www.sun-sentinel.com/sports/miami-dolphins/fl-sp-dolphins-ballage-transcript-20180428-story.html}{believes he's found motivation in being overlooked}.

  “In my opinion, I don’t believe there are 130 guys that are better than me and definitely not 11 other running backs. It’s fuel to the fire and motivation for me and I’m just excited about the opportunity.”

  Ballage is just a fourth round pick and though the odds are he won't be cut, if I were him I think I'd just be motivated to find playing time with the Dolphins instead of worrying about what other teams thought.
  
\item The Dolphins have one massive hole in their roster which they did not address:  defensive tackle.  Tannenbaum siad they're happy with what they have at the position and, fair enough, 2017 5th round pick Davon Godchaux shows promise.  But depending upon Jordan Phillips to fill the void on the other side is a recipe for disaster.   At 229 pounds, new linebacker Jerome Baker is going to need some help from his defensive linemen to keep him clean and allow him to make plays.  I'm having a hard time seeing it.
\item  I simply cannot understand this organization's stubborn insistence that Phillips will eventually develop the consistency needed to start and play at a competant level in what will now be his fourth year on the team.  These delusions that this 2015 second round pick is anything be a situational backup are disturbing.  Sticking with your draft choices just because they're your draft choices in the face of years of evidence that they simply can't play is the bad look for this front office at a time when the owner is reportedly losing patience with the franchise's directon.

  I can't imagine a well-run, elite frachise sticking with Phillips year after year with a faith bordering on the religious that he'll finally  fulfill what they say is his potential.

  It is not an exaggeration to say that Ndamkong Suh literally stopped the run over the entire half of whichever side of the offensive line he was on in the face of constant double teams.  And the Dolphins still were below average to poor stopping the run in recent years.  Without him now and without an adequate replacement, the problem is going to be even more acute.  The effect of losing those double teams on the inside is going to hurt Cameron Wake's sack production as well.

  Even with the addition of Fitzpatrick, this defense took a step back in the off season.
\item I went through the entire NFL draft with post-selection comments and didn't hear or read the phrase ``alpha male'' once.  Let's hope we've heard the end of it.

  Every team in nearly all competitive sports is, to some extent, a reflection of its head coach.  It's no coincidence that the Dolphins players pointed the thumb and held themselves accountable when Adam Gase was doing the same during the 2016 season.  It was not at all uncommon to hear Gase say in a post game press conference that he could have called a better play or could have done a better job of putting a player into a better positon to succeed.  Then Gase stopped doing that in 2017 and its no coincidence that complaints in the locker room about players not being accountable followed.  Things like having an offensive line coach snorting coke before team meetings also certainly didn't help.

  Gase has to stop calling upon players to be leaders and to start setting an example by being a better leader himself and his coaches have to do the same.
  
\item Want to have a little fun with a Bills fan in your life?  Go up to him and point to #7 overall pick Josh Allen and whisper two words:  ``Jay Cutler''.  Just don't do it unless you have an extra pair of pants on hand for them to change into.

  Coming out of Vanderbilt, Cutler had loads of talent but never was able to win at the college level.  The excuse was that he was surrounded by mediocre players.  But his penchant for losing followed him to the NFL level anyway and his potential never translated to much in the way of playoff wins.

  Allen performed horribly whenever he was faced with a Power 5 conference foe at Wyoming.  He might be able to correct flaws which have led to some terrible accuracy issues in college.  But can you make a winner out of a guy who was a career loser when the heat was on?  The Bills have bet big on it.
  
\item Overall this looked ot me like a pretty poor draft in terms of talent and I certainly wasn't alone in that assessment.  But what counts more than my opinion or anyone else's is what the NFL evaluators think.  In this regard, the reaction of the Patrios to this draft was interesting.  The Patriots had such a hard time finding players that provided adequate value in this draft that they made 8 draft weekend trades.  If their reaction is any indicaiton, this could be one of the worst drafts in modern NFL history.
  
\item I find that I often see eye-to-eye with Dave Hyde at the \textit{Sun-Sentinel} and \href{http://www.sun-sentinel.com/sports/miami-dolphins/97013953-132.html}{his reaction to this offseason} is no exception.  When I look at the talent that the Dolphins ahve lost in the off-season, I am facinated.  Head coach Adam Gase has gone all in with the notion that if he gets guys who will do it right, he can win games with Xs and Os. He has sacrificed a great deal of talent to test the theory.

  The notion that you can win a game with brains over braun and with hard work instead of a more talented roster is so extremely appealing to the average sports fan.  Doing it with guys who just do their job and work as a team is what its supposed to be about.  There's a huge part of me that really wants this to be true.

  But there's also this huge part of me that is really wary.  Everything in the NFL is dependent upon execution and there's no doubt that knowing where you need to be and making getting to that spot your highest priority is a big part of it.  But if you're opponent is more talented than you, don't they have a better chance of being capable of executing their part of the plan than you do?

  Can good coaching overcome a talent deficit?  Yes.  To an extent.  Do the Dolphins have enough of that kind of coaching?  Buckle up because we're about to find out.
  
  \end{enumerate}
