* *Tasks*
** DONE [#A] Schedule another S&R administrative team meeting
:PROPERTIES:
:SYNCID:   73BE83A0-0D3E-45CE-9427-715555D74B53
:ID:       55B4FC21-3712-4F6C-8BEA-5ECBF096A45F
:END:
** DONE [#A]  Look over and send edits to Princess [[message://%3c1565075017470.60238@rush.edu%3E][email to CD for Workload Evalution]]
:PROPERTIES:
:SYNCID:   330665E1-791E-4C06-B6EC-A258390EAE7D
:ID:       1E310000-381E-417B-8E16-E2F4770CF308
:END:
:LOGBOOK:
- State "DONE"       from "WAITING"    [2019-08-07 Wed 10:12]
- State "WAITING"    from "TODO"       [2019-08-06 Tue 07:58] \\
  Sent back to Princess with suggested edits.
:END:
** DONE [#A] Send Objectives for Intro to the ECG to Princess
:PROPERTIES:
:SYNCID:   6F475D49-CB04-4948-8D83-F8B1696C62FF
:ID:       369F599A-2033-4487-9AF4-FC2AA114FEAA
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2019-08-13 Tue 13:45]
- Note taken on [2019-08-13 Tue 13:45] \\
  1.  Explain how the cardiac action depolarization and repolarization propagates through the heart.
  2.  Explain how the EKG is measured from the electrical potentials generated outside the cardiac cells.
  3.  Explain how the propagation of the cardiac action potential correlates with the wave-form of the EKG e.g. p-wave (atrial depolarization), PQ interval (AV nodal delay), QRS wave (ventricular depolarization) and T-wave (ventricular repolarization).
:END:
** TODO [#A] FU Princess on posting objectives and get back to Mira and the other student [[message://%3c9256c7b6814f47c4a07b9612a47bbf6e@RUPW-EXCHMAIL02.rush.edu%3E][Course Objectives for RMD 566]]
:PROPERTIES:
:SYNCID:   FC24C8F8-7E51-4FF1-8D93-909573C779BA
:ID:       AE73884D-D8B9-4E5B-9A76-A42A77AABC6D
:END:

* *Ticklers*
** DONE FU Princess on workload assessment
SCHEDULED: <2019-07-29 Mon>
:PROPERTIES:
:SYNCID:   38A2F553-465C-4432-883C-1C13EF4EA7B6
:ID:       7EEDFBAC-F16A-472F-B6A3-50502E23439D
:END:
:LOGBOOK:
- State "DONE"       from              [2019-08-07 Wed 08:24]
- Note taken on [2019-07-24 Wed 08:10] \\
  [2019-07-24 Wed] Princess said she was going to get back to me yesterday but she's out of town at a meeting.  I guess I'll bug her Monday.
:END:
* *Meetings*
** Sexuality and Reproduction/Vital Fluids Administration Team Meeting; Location: AAC 403, Large Conference Room <2019-08-12 Mon 14:30-15:00>
:PROPERTIES:
:SYNCID:   B7812A3E-A828-4A05-ABAC-3FC1400DFFAB
:ID:       ACCA3ED1-C59D-48BC-A027-A61624C7C55E
:END:
:LOGBOOK:
- Note taken on [2019-08-13 Tue 07:42] \\
  Danesha didn't show.  Will track her down today.
  
  Went through ToF with Princess and we are on the same page with the topics.  Will go over more this afternoon.
:END:
*** Find out from Danesha what's happening with BCS.  FU on Oral Presentaion workshop and whether that mateiral is ready to post.
*** How was the research course handled last year?  We're doing it the same?  Bill has tlalked about setting up an Entrada shell for it.
*** Ask Princess and Jeffrey about imaging topics for MI.  Is this actually practitioner or anatomy?  The folder is empty and I don't know who, if anyone, to bug.
*** FU:  Infertility Self-Study
* *Notes*
