** TODO Aaron Rogers Undermines HIs Head Coach Every Time He Opens His Mouth.

#+BEGIN_EXPORT latex
\textbf{Mike Florio} at \textit{profootballtalk.com} on Green Bay quarterback \textbf{Aaron Rogers} \href{https://profootballtalk.nbcsports.com/2019/08/13/aaron-rodgers-attributes-outside-noise-to-fake-news-and-clickbait/}{characterizing} critical comments that he's creating ``outside noise'' as ``click bait'':

\begin{quote}
  ``If Rodgers doesn’t want to be 'put in that news cycle,' he should quit saying things that naturally flow into that news cycle. When he complains to \textbf{Mike Silver} of the
NFL that Rodgers wants more freedom at the line of scrimmage than the [head coach \textbf{Matt}] \textbf{LaFleur} offense gives him, Rodgers puts himself in that news cycle. When Rodgers
complains to reporters about joint practices and, more surprisingly, specifically says it’s not 'smart' to have close-to-live kickoff drills that are sure to catch the attention
of the NFL Players Association, Rodgers puts himself in that news cycle.
\end{quote}

It more than that.  Rogers is using the media as a weapon to undermine the head coach.

He wants more freedom at the line of scrimmage?  He doesn't work it out with LaFleur internally.  Instead, he runs to the media and complains.  The next thing you know, Green Bay fans are saying, ``Yeah.  He's a veteran, he should be able to change the play.''

That adds pressure on LaFleur to change his policy, even though he knows the way he runs his offense will work if given a chance.  In the mean time, the whole issue undermines his authority with both the fans and the media.

Rogers is playing LaFleur and their fans like a fiddle.  And he's using the media to do it.

Fortunately, the media knows when its being used though they didn't bother to try to point it out while former head coach \textbf{Mike McCarthy} was the victim, at least some are apparently trying to give LaFleur a little bit more of a chance.  For now.
#+END_EXPORT
