* Bears Need to Overcome Effects of Mini-Bye and Stay Sharp
#+BEGIN_EXPORT latex
\textbf{Colleen Kane} at the \textit{Chicago Tribune} \href{https://www.chicagotribune.com/sports/football/bears/ct-spt-bears-giants-prince-amukamara-20181127-story.html}{addresses one of the major challenges the Bears face as they ride the wave of their recent success}:


\begin{quote}
"As the Bears look to extend a five-game winning streak this weekend, their new challenge is staying sharp in the face of mounting success and praise.

“For a while people were saying that we weren’t a very good football team,” defensive end Akiem Hicks said. “And now on this side you have people hopping on the bandwagon and saying, ‘Oh, man, I’ve been a Bears fan since I was 12.’ It’s awesome. And there are people who have been riding with us through the whole thing.

“You have to remember what got you here. You have to remember the work and the time that you invested to get to this point. And I guess why stop now? Why stop now? When you’re on the top of the division, why pull back?”"
\end{quote}

Kane: \href{https://www.chicagotribune.com/sports/football/bears/ct-spt-bears-giants-aaron-lynch-20181128-story.html}{answers your questions}:


\begin{quote}
"But Nagy also said he is not concerned about his group letting up after winning three NFC North games in 12 days. He said the Bears could have let up because of their short practice week last week and didn’t.

“That teaches me who they are, and they’re grown men who understand where we’re at now,” Nagy said. “They take this game very seriously. They understand they need to be professionals. Right now we have put ourselves in this spot, and it’s my job to make sure that we stay in it.”"
\end{quote}





#+END_EXPORT
