* Bears Chances of Keeping Fangio Remote but Not Zero
#+BEGIN_EXPORT latex
\textbf{Brad Biggs} at the \textit{Chicago Tribune} \href{https://www.chicagotribune.com/sports/football/bears/ct-spt-bears-vic-fangio-head-coach-demand-biggs-20181227-story.html}{suggests that its possible that the Bears could keep defensive coordinator \textbf{Vic Fangio} happy in Chicago}:


\begin{quote}
"The Bears aren’t in the business of ripping up contracts for players or coaches but they might have to think outside the box if Fangio is weighing options in the next few weeks. If the Bears can pay to rebuild Halas Hall, they at least can make Fangio an offer that is hard to refuse. It wouldn’t be unprecedented — one of the reasons \textbf{Josh McDaniels} did a U-turn last offseason on his way to Indianapolis after the Patriots’ Super Bowl loss was because of a pay raise."
\end{quote}

It was one of the reasons.  But by all accounts, McDaniels staying had more to do with speculation that there was an agreement that McDaniels would succeed head coach \textbf{Bill Belichick}.

And becoming a head coach is really what its all about.

I have a hard time believing that there is anything that the Bears could do to keep Fangio from leaving Chicago if a head coaching position was offered elsewhere.  Its the pinnacle of the profession and there are few coaches who would feel fulfilled professionally with anything less if the opportunity to move up arose.

But that doesn't mean that there isn't any hope.  Right now the trend in the NFL is toward offensive head coaches.  The success of \textbf{Matt Nagy}, \textbf{Kyle Shannahan} and \textbf{Sean McVay}, not to mention old hand \textbf{Andy Reid}, has undoubtedly put owners and general managers in the mood to follow the lead of these teams.

In particular, offensive head coaches who can coach quarterbacks will be in high demand.  Because more and more it becomes evident that is what the game is about and there are few losing teams who won't either be looking for one somewhere or who won't be looking to develop one that they already have.

\begin{tabular}{lll}
  \textbf{Team Potentially Looking for Head coach} &\textbf{Likely 2019 Draft Position}* & \textbf{Likely 2019 Quarterback}\\
  Arizona &1 &Josh Rosen\\
  New York Jets &3 &Sam Darnold\\
  Tampa Bay &6 &Jameis Winston or draft pick\\
  Jacksonville Jaguars &8 &draft pick\\
  Carolina Panthers &10 &Cam Newton\\
  Cincinnati &12 &Andy Dalton\\
  Miami &13 &draft pick\\
  Denver &14 &Case Keenum or draft pick\\
  Green Bay &15 &Aaron Rogers\\
\end{tabular}

,* from \href{http://www.espn.com/nfl/draft2019/story/_/id/25117609/2019-nfl-draft-order-projected-first-round-picks-1-32-date-tracker-results}{ESPN Dec. 23 projections}

Of the nine teams either looking or who will be most likely to be looking for a head coach, only Carolina, Cincinnati and Green Bay have a firmly established starter and I'd say both the Bengals and the Packers may still take one with an eye towards developing him for the future.  

Even the Packers, who are rumored to be interested in Fangio, are are said to be already happy with defensive coordinator \textbf{Mike Pettine} and will undoubtedly be looking to inject some originality into what was perceived as a stale offense under former head coach \textbf{Mike McCarthy}.

Almost all of these teams certainly understand that the only way to keep a fertile offensive mind is to make him the head coach.  Anyone else who is any good will almost certainly be pilfered the minute a head coaching position is open.

In this environment that even a very, very good defensive coordinator will ultimately be chosen for a head coaching position is not a given.  And as a defensive coordinator Fangio seems happy in Chicago.  I have to believe that the only place Fangio would leave for is his home in the bay area. And that would be assuming his contract was up as the Bears would almost certainly never give him permission to leave for such a position.

So it's going to be an interesting offseason and Fangio will undoubtedly get his share of interviews for head coaching positions.  But I would say that Bears fans shouldn't give up hope that Fangio will happily stay where he is absent a better offer.
#+END_EXPORT
