#+BLOG: my-blog
#+POSTID: 5666
#+DATE: [2018-12-29 Sat 10:37]
#+Title: Quick Comments: Bears at Vikings 12/30/18
#+CATEGORY:  Chicago Bears, Minnesota Vikings

* Defense

1. The Vikings came out in the no huddle, evidently thinking that they could take the Bears by surprise.  It didn't work as they went three and out.
2. The Bears defensive line is pretty good.  The Vikings offensive line is not very good.  That's a bad combination if you are a Minnesota fan.  It was basically the story of the first half.
3. The Bears defense played pretty well in a game where the Vikings had everything to play for and the Bears had less and less to play for as the game went on.  They were pretty fundamentally sound, where, frankly, the Vikings offense wasn't.

* Offense

1. Unlike the Vikings, who came out with three straight passes, the Bears ran the ball on the first two plays right behind guard Kyle Long, back from his injury.  The Bears only threw once on the first drive, which went for a touchdown.  The Vikings eventually shut the run down and it became a field position game.
2. Jordan Howard definitely looks hurt to me.  He was lumbering on a long run in the first series in the open field.  Tarik Cohen would have made it a touchdown.
3. The Bears took three time outs, two in the first half, before the play clock ran out.  One of them came after a delay of game.  That's not a good look.  This is week 17 and you are headed to the playoffs, folks.  You are supposed to have your act together.
4. Kudos to Mitch Trubisky for throwing some very accurate deep balls, a couple of which should have been caught.  He had a good game.

* Miscellaneous

1. Joe Buck, Troy Aikman and Erin Andrews did a reasonably good job, I thought.  They were surprisingly critical of Kirk Cousins, implying that he was too tightly wound.  It turned out to be prophetic as there was a lot of arguing going on on the Vikings sideline at one point near the end of the first half.
2. Special Teams
   1. The Vikings punter, Matt Wile, should get a nomination for most valuable player for this game.  He had some beauties including one for 65 yards and one for 56 that put the Bears back at their own 12 yard line.
   2. Meanwhile Cody Parkey missed another extra point.  Shaky field goal kicking is a serious issue entering the playoffs.  Its very frustrating.

3. The Vikings had a couple of huge drops in this game on third down.  It had a significant impact on the game.  The Bears had a couple deep balls that should have been caught but the coverage was good and they would have been good catches.

4. Penalties

   1. Deon Bush had a bad face mask penalty that gave the Vikings the ball in field goal range near the end of the first half.  They converted it.

   2. Prince Amukamura had a couple of bad pass interference penalties.  He's got to stop all of the grabiness.

   3. Not a great decision by Mike Zimmer to throw the challenge flag late in the third quarter.  The Vikings were going for it on fourth and one and appeared to get the first down on a Cousins quarterback sneak.  Zimmer threw the flag right before the snap.  He lost the challenge, the time out and the first down.  They did eventually get the first down and the touchdown.

5. No turnovers this game.  So it was clean in that respect.

6. They should really outlaw yellow gloves like those worn by Vikings running back Dalvin Cook.  They look too much like penalty flags.

7. The most striking things about this game was the huge disparity in time of possession.  The Bears had the ball almost twice as long as the Vikings.  The offense played reasonably well and the defense played very well under circumstances when they really didn't have much to play for.  A very surprising win for the Bears as they have some momentum going into the playoffs.
