* Bears Shouldn't Forget About Guard in the Offseason
#+BEGIN_EXPORT latex
\textbf{Brad Biggs} at the \textit{Chicago Tribune} Its a little early with what we all hope will be playoff football yet to be played but \href{https://www.chicagotribune.com/sports/football/bears/ct-spt-bears-rams-blueprint-ryan-pace-biggs-20181207-story.html}{gives some brief consideration to some things that the Bears need to consider in the offseason}:


\begin{quote}
"The Bears don’t have many holes to consider in 2019. They will likely prioritize re-signing nickel cornerback \textbf{Bryce Callahan}, who will be an unrestricted free agent. Right tackle \textbf{Bobby Massie} and strong safety \textbf{Adrian Amos} are in the final year of their contracts, and \textbf{Matt Nagy} will likely want a running back to replace \textbf{Jordan Howard}."
\end{quote}

It all depends on the budget but I'd agree that Callahan is the priority.  Though I would agree that the Bears need to do something at running back, I'm not ready to give up on Howard, either.  I'm not sure what the problem is but I've seen running backs pull out of slumps before after an offseason of healing and training.  Howard doesn't seem to have the vision this year that he had last year but given that he's done it before, I'm guessing its fixable.  I'm also not ruling out the possibility that there's an injury there that's affecting his explosiveness.

So, assuming that they resign Callahan (a big assumption), that's one hole at running back to be filled.  They're likely going to see if either Massie or Amos can be signed to reasonable contract.  Both are solid but not spectacular and you could look to upgrade either or both positions.

The one position that's bugging me, probably because its a point of weakness right now, is guard.  It looks like \textbf{James Daniels}, \textbf{Cody Whitehair} and \textbf{Kyle Long} are your starters there but its now evident that the Bears have no depth behind them.  Just one injury to Long exposed the Bears at this position.  Its obvious that \textbf{Eric Kush} isn't as good as they thought he was and \textbf{Bryan Witzmann} has been a problematic replacement.  So, though it isn't as obvious as the potential holes in the starting line up that Biggs rightly prioritizes, the interior of the line is going to need to be addressed some how.


#+END_EXPORT
