* Quick Comments:  Bears at Eagles <11-26-2017>            :Bearing_the_News:

\subsection{Defense}
\begin{enumerate}
\item The Eagles come out mixing it up.  They executed pretty well all
  game, to say the least.
\item The Bears pass rush was anemic all game unless they were
  blitzing.
\item Speaking of the blitz, Wentz is pretty elusive in the pocket.
  Sort of Tom Brady-esque there.
\item The Eagles did a good job against that blitz in general,
  frequently taking advantage for some big gains.  The bears weren't
  getting there quick enough.
\item What's really bad is that the Bears were playing a light box and
  they still struggled to cover the Eagles receivers.  The Eagles took
  advantage with some good long runs.  By the end of the first quarter
  and the Eagles were rolling both on the ground and through the air.
\item It certainly doesn't help that the Bears were manhandled at the
  line of scrimmage.
\item Christian Jones looked pretty good in coverage this game.
\item It was interesting watching the rookie Eddie Jackson giving
  Prince Amukamara hell for not trying to knock Alshon Jeffery off of
  his route after a catch where Jackson didn't have time to get over
  to help.  In truth, it was a common problem for the cornerbacks.
\item Kyle Fuller was having a hard time keeping his footing out there
  in the first half.  I'm wondering if he had the wrong cleats on.
\item Zach Ertz obvioulsy had a good game as the Bears safeties had a
  hard time matchng his physicality.
\end{enumerate}

\subsection{Offense}
\begin{enumerate}
\item Here's all you need to know.  The Bears didn't have a first down
  until 2 minutes into the third quarter.  The first half time of possession was
  20:03 to 9:50 Eagles.

  This was the most disgusting offensive performance I've seen all
  year.  The offense totally hung the defense out to dry.  The whole
  unit should apologize.
  
\item The Bears tried to continue to open up the offense and came out
  throwing on first down.  Unfortunately Trubisky was struggling with
  his accuracy, as has been his wont of late.
\item The Bears had a very hard time running the ball against the
  Eagles number one rush defense.  No great surprise.
\item The Bears really struggled to block the Eagles.
\item It didn't help that the Eagles looked so well coached, correctly
  reading the plays as they developed and reacting quickly.
\item I like the idea of putting Trubisky in the pistol formation.  It
  gets him out from under center to a place where he's more
  comfortable and yet its easier to run out of.
\item One thing about Trubisky.  I've been tough on him for his
  accuracy and rightfully so.  But some of it is because he's trying
  to throw with anticipation to his receviers.  Perhaps it willpay off
  in the end as he gets better at it.

\end{enumerate}
  
  
\subsection{Miscellaneous}
\begin{enumerate}
\item Kevin Burkhardt, Charles Davis and Pam Oliver were your announcers.

  This was the team that Jay Cutler was supposed to be a part of and it would have been really interesting to have heard what he had to say.

  ``Hey, at least Trubisky doesn't have Martellus Bennett laying down
  on him and he doesn't have Brandon Marshall in his ear.

  ``Whatever.''
  
\item Pat O'Donnell had a pretty awful punt to set the Eagles up in
  Bears territory in the first quarter.  The possession resulted in a
  touchdown.  Another blocked punt gave the Eagles field position in
  Bears territory in the second quarter.

  Cairo Santos missed a 54 yard field goal by a mile wide right.

  Kicking wasn't the only problem.  Return teams were generally pretty
  miserable as the Bear were constantly in poor field position, often
  with a poor return in conjunction with a penalty.
  
\item There were plenty of penalties on both sides today.  Only one
  team was good enough to be able to afford them.

  Having said that, its not a big surprise that a defense coached by
  Jim Schwartz is undisciplined. The Bears are familiar with the way
  his defenses play, both good and bad, from his days as the Lions
  head coach.
\item Drops didn't play a huge role today.
\item One of the few really good things that the Bears did today was
  strip the ball.  It's a shame it
  didn't result in more points.

  Two turnovers took place on a bazaar play where Malcolm Jenkins
  intercepted another poor throw from Mitch Trubisky.  Interestingly
  Dion Simms got the ball back by stripping Jenkins, actually giving
  the bears better field position.  They were unable to take advantage
  of it as Adam Shaheen missed a block on 3rd and 2.

  Adrian Amos stripped the ball from LaGarrette Blount after a long
  run, giving the Bears the ball in Eagles territory.  That ended with
  a missed field goal.

  Cre'Von LeBlanc caused another fumble with a hit on Jay Ajayi on
  another weird play.  The ball went into the end zone where Nelson
  Agholor recovered it.

  Isaiah Irving recovered a fumble in the fourth quarter.

  Trubisky threw an interception late in the fourth quarter that was
  overturned to become an incomplete pass but not before the Eagles
  got to do a line dance on the field.  That was followed by a real
  pick and another dance.
  
\item This was totally domination in pretty much every way.  The Eagles
  not only have far more skill position talent, they dominated the
  Bears on both sides at the line of scrimmage.

  The Bears defense couldn't get off the field as they couldn't stop
  the Eagles on fourth down.  The special teams were a disaster. The
  offense couldn't execute and the rookie quarterback stunk.

  It's hard to argue that this team is improving after such a total
  disaster.  This was a tough one to watch - for fans and ownership.
  It's one that may factor heavily in John Fox's and maybe Ryan Pace's
  future unless this team starts showing a lot better soon.

  Right now they feel a long, long way off.
\end{enumerate}
