* Bears David Montgomery Strength?  He's All Football Player.

#+BEGIN_EXPORT latex
\textbf{Brad Biggs} at the \textit{Chicago Tribune} \href{https://www.chicagotribune.com/sports/bears/ct-cb-bears-panthers-brad-biggs-10-thoughts-20190809-65kaonc3rvebvhidtj2cxiwgeq-story.html}{on the performance of Bears rookie running back \textbf{David Montgomery} last night}:

\begin{quote}
  ``Six touches for rookie running back David Montgomery was all that was needed to feel really good about him — and the role he’s going to play in this offense.

``Montgomery already looked the part in training camp, running hard through tackles in some rare live action in Bourbonnais. But a chance to see him go against the Panthers,
albeit a brief chance, was enough to confirm what was expected. Montgomery looked really good in the open field. He looked good in the low red zone, running to daylight after a
jump-cut at the line of scrimmage on a 7-yard touchdown. He looked natural catching the ball. If you were seeking validation that general manager Ryan Pace made the right
move in paying a pretty hefty price to trade up and select Montgomery, this was a heck of a start.''
\end{quote}

My first impression of Montgomery is similar to what my first impression of former Bears running back \textbf{Jordan Howard} was - he isn't going to be running away from guys very often. And unlike Howard, Montgomery isn't particularly big though his center of gravity is lower to the ground than I thought it was.  But, similar to what I eventually concluded about Howard, I can see why the Bears like him.  Montgomery is a football player.  And that's probably more important than superior physical talent.

Don't get my wrong.  Talent is important and you have to have at least some of it to succeed.  But you don't have to be the fastest guy on the field.  In Howard's case, his ability to find small cracks in the line and to slip through to make gains was a huge strength for a big back.  It looks to me like Montgomery has some of that vision when he bounces the ball outside.  Defenses are going to have to play the run with discipline whenever Montgomery is on the field or he's going to burn them for big gains.

You can also see where Montgomery could succeed in the passing game.  Get him into space and his quickness and ability to break tackles starts to show itself.  He's got instincts and he runs with effort.

Yeah, the guy probably is going to get caught from behind a few times this year.  But overall, I like what I see and I think Montgomery's strengths could far out weight his weaknesses.  I see a guy who could quite possibly match the production of a \textbf{Matt Forte} as a very good running back that could provide yet another aspect to what is looking like its going to be a versatile offense.
#+END_EXPORT
