* Bears at Bengals 1017-12-10

\subsection{Defense}
\begin{enumerate}
\item The Bears came out covering the Bengals tighter than they did
  the 49ers last week.  They also seemed to be playing closer to the
  line of scrimmage than usual to stop the run.  It was an interesting
  decision considering that they were surely rotating their coverage
  over to cover AJ Green.
\item The Bengals finally started to run the ball effectively against
  a beat up Bears front seven late in the first quarter.  They easily
  worked their way down the field for a touchdown.
\item The Bears defensive backs are going to look back at the dropped
  interceptions that they had in this game and really be kicking
  themselves.  Prince Amukamara and Kyle Fuller (at least
  two) both dropped sure fire turnovers.
\item The Bears have developed a bad habit of allowing teams to get
  first downs on third down right at the sticks.  It seems like the
  coverage needs to tighten up in those situations.
\item You can certainly understand why Bengals fans might be
  frustrated by Andy Dalton.  His accuracy is about a inconsistent as
  it can be and still be from a NFL starter.
\item Not a great day for AJ Green.  The Bears corners had something
  to do with that but so did Dalton.
\end{enumerate}

\subsection{Offense}
\begin{enumerate}
\item The Bengals defense looked like they came out flat, probably
  because they were coming off of a huge game against the Steelers.
\item The Bears came out running the ball pretty well.  It didn't take
  the Bengals long to start stacking the line of scrimmage and
  challenging the Bears to throw the ball.  The Bears were glad to
  take the opportunity to finally do so against the soft, two deep
  zone that the Bengals like to play rather than the tight man to man
  they have been facing.
\item The Bears did a pretty good job driving late in the first half
  but, as has been their wont, once they got into the red zone they
  couldn't turn it into a touchdown.
\item Mitch Trubisky looked good today and, if he wasn't pinpoint all game, he was, at least, generally accurate.  He seems to read the field well and seemed to be finding the open man, especially if that man was open in the middle of the field where he was easy to see.
\item One thing I didn't like was how often I saw Trubisky throwing off of his back foot.  The throws weren't horrible but he's not driving the ball and the ball placement isn't as good as it should be when he does it.
\item It certainly helped that Trubisky was getting plenty of good protection.
\item To my eye, Trubisky showed a willingness to throw into tight
  coverage that wasn't always there earlier in the year as he was a
  bit more aggressive.
\item Terrible drop in the end zone aside, Adam Shaheen had a good ball game to give all of the fans a little hope.
\item Credit Michael Johnson with a couple good sacks but at the same time he took advantage of some miserable blocks.
\item Both Tarik Cohen (over 10 yds per carry) and Jordan Howard (over 145 yards) Really ran with good vision today.  Both had good days as the team as a whole had a good rushing day.
\item It was nice to see the Bears reverse the stat that was most reflective of last game by dominating the time of possession instead of being dominated.
\item Kendall Wright (10 receptions) had a really good day as well.
\end{enumerate}
  
  
\subsection{Miscellaneous}
\begin{enumerate}
\item Sam Rosen (play-by-play), Brady Quinn (analyst) and Jenny Taft
  (sideline reporter) were your announcers.  I love it when the
  Bears draw this announcing team.  I always know with complete
  confidence up front that I can just turn the volume down and I won't
  miss anything.
\item Mike Nugent was short on the opening kickoff.  Same thing with
  the kickoff immediately before half time after a Bears field goal.
  You wonder why they didn't keep Pat O'Donnell doing the kickoffs, as
  he seemed to do a pretty good job.  Nugent then proceeded to miss
  his first extra point with the Bears.  Great start [eye roll].

  Tarik Cohen seemed to be having a tough time judging the ball on
  punt returns.  Its possible the wind was up on the river front but
  either way he needs to be able to field those.
\item Why is that seemingly every time Tarik Cohen pulls off a big
  play, the Bears manage to crush it with a penalty.  They did it
  again in the second quarter as Cohen scored a touchdown on a 13 yard
  pass with a nice run after the catch.  The Bears ultimately settled
  for a field goal after making a circus out of what should have been 7 points.

  Seven penalties in the first half.  It's totally ridiculous.
\item Jordan Howard had a bad drop the first play from scrimmage for
  the Bears.  Adam Shaheen dropped a touchdown at the end of the first
  half.  That turned into a field goal.
\item Eddie Jackson had a nice interception on a Dalton ball that was
  knocked into the air.  That was followed by a nice job stripping the
  ball and recovering the fumble on a pass play near the sideline.
\item The Bears did a good job of beating the Bengals at the line of
  scrimmage today on both sides of the ball.  As is usually the case,
  the team that does that tends to be the better team overall for most
  of the game.  That was the case today.
\item I don't know that I've ever seen a team more flat than the
  Bengals were today coming off of that Monday Night war with the
  Steelers.  I hate to say it but there were guys out there that I
  frankly thought just didn't care.  It was just one week but that's a
  team that certainly looked like it's in need of an overhaul.  Based
  upon what I saw I don't like the look of Marvin Lewis's immediate
  future there.
\item The Bears were frustrating watch again this week, albeit for a
  different reason.  For once, the young talent with Jordan Howard,
  Adam Shaheen, Tarik Cohen, Eddie Jackson and Trubisky was evident
  against a flat and wounded Bengals team.  But their penchant for
  eliminating big plays with stupid penalties, ewspecially in the
  first half, held them back.

  There's something here to work with.  But these guys have got to
  execute better as a team.
\end{enumerate}
