* Bears Recievers                                            :bearingthenews:


\textbf{Brad Biggs} at the \textit{Chicago Tribune} \href{http://www.chicagotribune.com/sports/football/bears/ct-spt-bears-nfl-draft-mailbag-20180125-story.html}{answers your quesions}:

\begin{quote}
Will Kevin White and Cam Meredith be the third and fourth receivers or even make the team? This, assuming the Bears draft a wide receiver in the first or second round and acquire a star free agent. — @chuckietwoglove

I kind of doubt there are going to be a lot of “star” wide receivers available in free agency, but we will have to see what unfolds. It’s impossible to stack a depth chart right now and say who would be No. 3 or No. 4. I imagine the Bears will tender an offer to Meredith as a restricted free agent and, yes, White will be with the team this year. If they’re both healthy and playing like they were when they went down, you’d have to think Meredith would rate an edge ahead of White.
\end{quote}

The way I see it now, the Bears are in big trouble at wide receiver.

Like Biggs, I see nothing coming in free agency that would resemble
anything like a number one receiver.  Biggs also thinks that the wide
receivers at the top of the 2018 NFL draft offer very little potential, an
opinion that is
\href{http://www.espn.com/nfl/draft2018/insider/story/_/id/22170535/todd-mcshay-updated-top-32-prospects-ranking-2018-nfl-draft-new-no-1-not-quarterback}{echoed
  by \textbf{Todd McShay} at \textit{ESPN}} though that opinion
\href{https://ebonybird.com/2018/01/20/baltimore-ravens-good-year-need-wide-receivers/}{is
  not universally shared}.

Generally speaking, it looks like general manager \textbf{Ryan Pace}
has his work cut out for him.  The guess here is that he needs to find
a diamond in the rough in the middle rounds or the Bears will be
playing with a bunch of number 2's and 3's but without a true nunber 1 receiver in 2018.  Again.
