* Dolphins Reportedly Headed in the Wrong Direction in Head Coaching Search
#+BEGIN_EXPORT latex
If reports are correct, the Dolphins coaching search is currently headed in the wrong direction.

That's my conclusion one day after the Dolphins fired head coach Adam Gase.  According to the \textit{Sun-Sentinel} the Dolphins \href{https://www.sun-sentinel.com/sports/miami-dolphins/fl-sp-dolphins-coaching-search-20181231-story.html}{have five assistant coaches on their interview list} with varying backgrounds.  However, none of them has the right background.  They are:

\begin{tabular}{lll}
  Name &Current Position &Current Team\\
  Vic Fangio &Defensive Coordinator &Chicago Bears\\
  Eric Bieniemy &Offensive Coordinator &Kansas City Chiefs\\
  Brian Flores &Defensive Coordinator &New England Patriots\\
  Mike Munchak &Offensive Line Coach &Pittsburgh Steelers\\
  Kris Richards &Secondary Coach &Dallas Cowboys\\
\end{tabular}

There is no claim that this list is complete and I certainly hope that is the case.  Because none of these candidates has the one thing everyone, including Miami, needs:  an offensive head coach who can coach quarterbacks.

Right now the trend in the NFL is toward offensive head coaches.  And rightfully so.  The success of \textbf{Matt Nagy}, \textbf{Kyle Shannahan} and \textbf{Sean McVay}, not to mention old hand \textbf{Andy Reid}, has undoubtedly put owners and general managers in the mood to follow the lead of these teams.

\begin{tabular}{lll}
  Head Coach &2018 Playoff Team &Former NFL Coaching Position\\
  Kansas City &Andy Reid &Offensive Coordinator\\
  New England &Bill Belichick &Defensive Coordinator\\
  Indianapolis &Frank Reich &Offensive Coordinator\\
  Houston &Bill O'Brien &Offensive Coordinator\\
  Los Angeles Chargers &Anthony Lynn &Offensive Coordinator\\
  Baltimore &John Harbaugh &Special Teams Coordinator\\
  New Orleans &Sean Payton &Quarterbacks Coach\\
  Los Angeles Rams &Sean McVay &Offensive Coordinator\\
  Philadelphia &Doug Pederson &Offensive Coordinator\\
  Chicago &Matt Nagy &Offensive Coordinator\\
  Seattle &Pete Carroll &Defensive Coordinator\\
  Dallas &Jason Garrett &Offensive Coordinator\\
\end{tabular}

Of the twelve 2018 playoff teams above, nine have offensive backgrounds including three of the four top seeds (Belichick is always the exception, isn't he?).  Of those nine, all but Sean McVay and Anthony Lynn have a background coaching quarterbacks. 

And given those numbers, offensive head coaches who can coach quarterbacks should be in high demand.  Because more and more it becomes evident that is what the game is about and there are few losing teams who won't either be looking for one somewhere or who won't be looking to develop one that they already have.

\begin{tabular}{lll}
  \textbf{Team Potentially Looking for Head coach} &\textbf{Likely 2019 Draft Position} & \textbf{Likely 2019 Quarterback}\\
  Arizona &1 &Josh Rosen\\
  New York Jets &3 &Sam Darnold\\
  Tampa Bay &5 &Jameis Winston or draft pick\\
  Denver &10 &Case Keenum or draft pick\\
  Cincinnati &11 &Andy Dalton\\
  Green Bay &12 &Aaron Rogers\\
  Miami &13 &draft pick\\
Cleveland &17 &Baker Mayfield\\
\end{tabular}

Of the eight teams looking for a head coach, only Cincinnati and Green Bay have a firmly established starter and I'd say both the Bengals and the Packers may still take one with an eye towards developing him for the future.  

Almost all of these teams certainly understand that the only way to keep a fertile offensive mind is to make him the head coach.  Anyone else who is any good will almost certainly be pilfered the minute a head coaching position is open.

Yes, Miami tried this once with Adam Gase and it didn't work.  But the fact that Gase wasn't the guy shouldn't deter them from doing it again.  And again and again and again.  Until they get it right.

Miami should be looking to do two things in the offseason:  draft a quarterback and hire someone who can coach him.  The odds of winning consistently without both are low and the best way to establish stability is to make the second is the head coach.  And that's what they should be trying to do.



#+END_EXPORT
