* Robbie Gould Post                                          :bearingthenews:


\textbf{Brad Biggs} at the \textit{Chicago Tribune} \href{http://www.chicagotribune.com/sports/football/bears/ct-mitch-trubisky-jimmy-garoppolo-bears-mailbag-20171102-story.html}{answers more of your quesions}:

\begin{quote}
I was baffled when the Bears cut \textbf{Robbie Gould} and felt it would come
to haunt them. Now it seems obvious it was a mistake. Your thoughts? —
@stewart_errol

Gould has been excellent for the 49ers this season making 17 of his 19
field-goal attempts. Gould missed two extra points in the preseason
finale of 2016 for the Bears, one of which was blocked, and you should
recall there were some key late-season misses for him in 2015. \textbf{Connor
Barth} hasn’t been as good as the Bears would like and we’ll have to
see if he can straighten things out in the second half of the
season. I’d imagine it’s more or less a week-to-week proposition for
him at this point. I’d also say that the Bears have made bigger
personnel mistakes than at kicker. They’ve got bigger need-to-fix
projects right now than kicker and it’s not like there are necessarily
great options on the street. As I pointed out in 10 Thoughts following
the Saints game, the kicker to keep an eye on right now is \textbf{Cairo
Santos}. Unfortunately, he’s not healthy as he recovers from a groin
injury that led the Chiefs to release him.
\end{quote}

I'm sure a lot of fans still have this quesion.  From what we could
seen, Gould was an excellent kicker and no one could possibley look at
the situation and say the Bears did the right thing.

But here's the deal.  Fans don't see everything. In particular, we
odn't see wht goes on in the lockerroom.  Anf that might have had a
lot to do with Gould not being in Chicago.

Gould was the Bears longest tenured player which probably made him set
in his ways, as people who are in the same job for a long period of
time are apt to be.  To add to that, Gould was definitely opinionated
and
\href{http://bearingthenews.com/blog/2016/09/10/problems-signing-josh-sitton/}{was
  not shy about sharing it}.

The guess here - and it pure specualtion - is that Gould had an
attitude and one that special teams coordinator \textbf{Jeff Rogers}
didn't particularly like.  The Bears had (and have) a young team and they undoubtedly wanted their players exposed to the right influences.

Its possible that, for whatever reason, they didn't deem Gould to be
the right guy to have around.  in any case fans, who are on the
outside looking in, are are unlikely to ever find out exactly what
that reason was.
