* Panthers at Bears					   :Bearing_the_News:
\textbf{Defense}
\begin{enumerate}
\item The Bears started this game stacking the run on first down but
  eventually the Panther's started spreading them out, then attacking
  them up the middle.  Presumably they were going after Christian
  Jones.  To a certain extent, it worked.
\item Other than that, I thought the Bears did a good job of stopping
  the run generally.
\item Kyle Fuller had another excellent game.  Eventually the Panthers
  started going to the other side at Prince Amukamara with a bit more
  success.  They also attacked Bryce Callahan over the middle with
  some success.
\item They'd have had more success but Cam Newton wasn't having one of
  his better days.  He wasn't very accurate and that certainly helped
  the Bears cause.
\item Kudos to the Bears front seven as they got sack after sack on
  Newton.  Akiem Hicks, Leonard Floyd and Danny Trevathan all had
  sacks.  That certainly helped as well.  They took advantage of some
  bad Carolina blocking through the first quarter and a half.  It got a
  little better after that to my eye.
\item Trevathan really showed up again and had a very good game.
  He was particularly effective on the blitz.
\item The Bears defense looked tired at the end of the first half.  It
  was their own fault.  Carolina dominated the time of possession
  (22:21 Vs 7:39) largely because the Bears kept scoring on defense.
\item Floyd had a good game getting pressure but I got a
  little tired of watching him take an inside path to the quarterback,
  thus letting Newton extend plays outside the pocket.
\end{enumerate}

\textbf{Offense}
\begin{enumerate}
\item The Bears didn't get the ball on offense until 7:46 was left in
  the first quarter because the defense was coring and giving the ball
  back to the Panthers.
\item The Panthers stacked the line of scrimmage when they saw triple
  tight end but mostly they played light in the box.  you'd think the
  Pittsburgh tape would have told them not to do that but...
  whatever.
\item The Bears are so bad at wide receiver that they basically made
  Tarik Cohen into one today.  Whenever he and Jordan Howard were on
  the field at the same time, the Panthers were smart enough to treat
  him like one as well and put the nickel defense on the field.  Cohen
  still had a huge 70 yard reception setting up a field goal.
\item Mitch Trubisky is still holding the ball too long. He had a sack
  at the end of the first quarter that put them back to the limit of
  Connor Barth field goal range at the 34 yard line.  Barth missed it.
  He can't take a sack there.
\item Not a great day for Trubisky today.  He was under pressure on third and long with a blitz coming where he really needed to get rid of the ball.  He looks like he just doesn't know where to go with the ball, yet.
\item I like the way that the Bears will occasionally go into the
  hurry up to prevent Carolina from substituting.  It works.
\item Cody Whitehair is really having problems this year.  In addition
  to the bad snaps before this game, he's been getting pushed around
  quite a bit more than you'd like up front.
\item Did OK but they allowed too much penetration in some important spots today.
\end{enumerate}


\textbf{Miscellaneous}
\begin{enumerate}
\item Ian Eagle and Dan Fouts
\item Connor Barth had a 42 yard field goal blocked.  It looked like
  it came out low.
\item The Bears did a reasonable job here, limiting penalties until,
  of course the offense had to actually come through and try to help
  put the game away.  Then it was a flag fest.
\item Cohen had a drop in the first quarter..
\item Eddie Jackson had a banner day in the run over department scoring
  on a long fumble recovery and then on a pick six, both over 70
  yards.  Credit Amukamara on the assist on the lick six as he tipped
  the ball into the air with some good coverage.  Trevathan had a huge
  interception midway through the fourth quarter.  The Bears once
  again did a good job here and it was key to keeping them in the
  game.
\item This was a terrible offensive game for the Bears today.  They ran just 37 offensive plays and converted exactly two third downs.  They had the ball six times in the second half and all but the last one were three and outs.  They held the ball for only 21:25 and hung the defense out to dry, leaving them on the field for 38:35 to wear down to a nub.  This just has to get better.

  On the bright side the defense played great today and really carried the day.  They not only accounted for stopping the Panthers but they did almost all of the scoring, as well.  Those guys were heros today.

  If you want the bottom line, its in the usual stats.  The Bears won the turnover battle (2-0), They had few penalties (only 2) and they didn't drop the ball much if for no other reason than there were so few passes.  The Bears don't have a big margin for error but they played reasonably well on a day that Cam Newton really didn't.  That was enough.
\end{enumerate}
