* NFL Draft prospects                                   :NFL_draft:
\subsection{Ohio St. - Michigan}
\begin{itemize}
\item Michigan’s Maurice Hurst 6'2'', 280 lb 73
  \begin{itemize}
    \item Looks like a 4-3 DT.
    \item 
    \end{itemize}

\item Ohio State center Billy Price 54
\item Michigan David Long 5'11'' 187 lb 22 - at least one play where he played zone and everyone else played man.  Knuckle head?
\item Michigan Lavert Hill 5' 11'' 177 lb 24
  \begin{itemize}
    \item both corners press a lot
  \item Neither has ideal size
    \item Ohio St. not really enen challenging these guys early.
    \item Willing tackler
    \end{itemize}

\item Ohio St. Nick Bosa 97
  \begin{itemize}
  \item undisciplined, always looks like he's rushing the QUARTERBACK, even against the run.
  \item collapses in and leaves the edge open.
  \item Goes inside on passing downs
    \item Looked like he was supposed to cover the tight end on the
    second Michigan touchdown.  He fell down but it was interesting
    that was the way that they were using him.  Obviously an athlete.
  \end{itemize}

\item Michigan left tackle Mason Cole 52
\end{itemize}
