* This was never posted.

#+BEGIN_EXPORT latex
\textbf{Colleen Kane} at the \textit{Chicago Tribune} \href{http://www.chicagotribune.com/sports/football/bears/ct-spt-bears-helmet-rule-vic-fangio-20180731-story.html}{quotes Bears defensive coordinator \textbf{Vic Fangio} and special teams coordinator \textbf{Chris Tabor}} on the new NFL helmet contact-rule:

\begin{quote}
  ``'It’s going to be an extremely hard play to officiate, other than the super obvious,' defensive coordinator Vic Fangio said Tuesday after the Bears’ final practice before the Hall of Fame Game against the Ravens on Thursday.''

``'We’re going to have to change a little bit as we go throughout the year,' Tabor said. 'And as penalties arise from that play, I think it will just be ‘teach tape’ for us in what they can and can’t do.'''
\end{quote}

One thing that you might expect to see during the Hall of Fame game is yellow flags flying all over the field.  If we do, I would advise fans not to panic.  Many riles changes like this get officiated pretty tightly during the preseason when officials are emphasizing them early.  They then tend to loosen up a bit once the season starts.

#+END_EXPORT
