* The Bears Seem to Be Feeling Run Down in the Fourth Quarter.  What to Do?
#+BEGIN_EXPORT latex
I'm not the only one that has noted that \href{https://www.chicagotribune.com/sports/football/bears/ct-spt-bears-three-keys-lions-mitch-trubisky-20181121-story.html}{the Bears defense seems to be getting tired in the fourth quarter}.  Bears defensive back \textbf{Kyle Fuller} admits it himself, \href{https://www.chicagotribune.com/sports/football/bears/ct-spt-bears-kyle-fuller-interception-lions-20181122-story.html}{albeit in a back handed way}:

\begin{quote}
"Fuller said the defense’s ability to come up with a big stop late during their third game in 12 days showed 'just how focused we are.'

“'(It was) blocking out how tired some people may say you are,' he said. 'It’s just locking in, going out there, doing what we do, playing hard and getting a win.'"
\end{quote}

I don't know who these ``some people'' are but given that the game is going on, it must be someone close during the game.

And it is generally evident that the Bears are getting tired.  In ten fourth-quarters alone, the Bears’ defense has surrendered 92 points, almost the same number as the total through the first three quarters (96).

There are a lot of reasons for this.  They have often been protecting a lead.  But generally speaking, the eye test tells me that they looks tired.

I'm not sure what the answer to this is but my gut tells me that the Bears have to have more faith in their back ups.  The statistics weren't available for the Lions game but \textbf{Khalil Mack} played 93\% of the defensive snaps in the Vikings game last Sunday.  \textbf{Leonard Floyd} played 84\%.  \textbf{Kyle Filler}, \textbf{Adrian Amos}, \textbf{Prince Amukamura}, \textbf{Roquan Smith} and \textbf{Eddie Jackson} all played every defensive snap and \textbf{Danny Trevathan} only missed one.

I get it.  You want to keep your best players on the field.  But \href{http://bearingthenews.com/blog/2018/11/22/what-has-exceeded-expectations-the-most/}{as I've previously written}, the Bears appear to me to have more depth than in previous years.  Perhaps its time to take advantage of it by playing some of the back ups just a little bit more to give the defensive players a breather.








#+END_EXPORT
