* What Is Decreasing Jordan Howard's Effectiveness
#+BEGIN_EXPORT latex
\textbf{Brad Biggs} at the \textit{Chicago Tribune} \href{https://www.chicagotribune.com/sports/football/bears/ct-spt-bears-bruce-irvin-kyle-long-mailbag-20181107-story.html}{answers your questions}:


\begin{quote}
" \textbf{Jordan Howard} has five touchdowns, on target for 10. Can we stop talking about how many yards the guy has and talk about bottom line: TDs and effectiveness? His influence on the offense from a scoring standpoint is about what it was last year. The coaches openly admit the run game isn’t optimized, so his production can be even better as the offense improves. — Jeff C., Parts Unknown

``I look at a lot of things before touchdowns when evaluating a running back. Howard could have six this season if he didn’t fumble at the goal line in Miami. It was uncharacteristic for him as he generally has excellent ball security. Howard has not been as explosive to the hole this season, and as I wrote last week, he’s also struggled creating yards after contact — although Bills safety \textbf{Jordan Poyer} might have a different opinion on that after Howard ran him over like a truck to score on an 18-yard run. I don’t think Howard has been as effective this season, and includes factors other than his touchdown total. Hopefully the Bears will be better on the ground in the next eight games."
\end{quote}

Biggs might have a point about Howard's explosiveness but it looks to me like he's also lost something in terms of his vision.  Last year Howard seemed to be slipping through cracks that I never saw until he was through them.  This year I'm spotting cut back lanes that Howard is missing.

The run game really hasn't changed that much as far as I can tell with the hiring of \textbf{Matt Nagy}.  It's a lot of zone blocking with a lot of inside zone runs for Howard.  But something appears to be throwing him off of his game and I don't think its just physical.  Here's hoping that whatever it is, he gets over it and and becomes more effective the second half of the season.
#+END_EXPORT
