* Will Fox's Input on Defense Be Missed
#+BEGIN_EXPORT latex
\textbf{Dan Durkin} at \textit{The Athletic} \href{https://theathletic.com/409905/2018/06/27/climb-aboard-the-bandwagon-why-its-ok-to-be-optimistic-about-the-2018-bears/}{gives fans reasons to be optimistic in 2018}:

\begin{quote}
  ``\textbf{Vic’s vision and voice} — [New head coach \textbf{Matt}] \textbf{Nagy}’s singular focus is installing his offense, so he’s handed over control to [defensive coordinator \textbf{Vic}] \textbf{Fangio}. Considering how well the defense played last season, despite minimal help from the offense in terms of points and time of possession, keeping things the same on defense was a wise decision. [Former head coach \textbf{John}] \textbf{Fox} was a defensive-minded coach who reportedly didn’t always see eye-to-eye with Fangio. With Fox fleeing, that allows Fangio to scheme and gameplan how he wants and be the single voice in defensive meetings and film sessions. That’s a win for the side of the ball most ready to compete.''
\end{quote}

I'm not so sure dismissing Fox's contribution on defense is entirely right here.  I can recall former head coach \textbf{Lovie Smith} allowing defensive coordinator \textbf{Ron Rivera} to depart after the Bears last Super Bowl apearance.  The defense that year was outstanding but Smith didn't like compromising on his game plans and resented Rivera's input.  Instead of viewing the situation as the positive which it undoubtedly was - a situation where creative tension resulted in outstanding performance on all sides - Smith chose to view Rivera as challenging his authority.  Smith brought in his own yes men at defensive coodinator after that and his defenses were arguably never quite as good for the loss.

I'm not saying the situation is quite the same here.  Fangio, himself, said that he virtually always got his way last year when he and Fox clashed.  That wouldn't be too surprising given Fox's evident tendency to let coaches do their jobs as long as they got results.  Nevertheless, it will be interesting to see if the abscence of input from Fox this year will have an effect on the defense.

#+END_EXPORT
