* *Tasks*
** DONE [#A] [[message://%3c0101016b2edbc78d-c4b67c3d-d751-40a4-9c11-2f06e1e990d9-000000@us-west-2.amazonses.com%3E][ACTION REQUIRED: FY19 Faculty Performance Evaluation Due,]]

- Note taken on [2019-06-07 Fri 08:58] \\
  This has to be complete before August 31 and will require parrts being filled out by both Beth and Mike.  So maybe getting it done by July 15 or so wouldn't be a bad idea.
** DONE Find out what this ticket is about.
[2019-07-07 Sun 05:27]

[[message:%3C0101016bc8dda57f-7454b94d-2f96-46a7-97b2-831db63d7efe-000000@us-west-2.amazonses.com%3E]]
** DONE Find out what this ticket is about.
[2019-07-07 Sun 05:27]

message:%3C0101016bc8dda57f-7454b94d-2f96-46a7-97b2-831db63d7efe-000000@us-west-2.amazonses.com%3E
** DONE [#A] [[message://%3c0101016bf20337e4-1dde3895-dab0-4bcd-bb33-af282a7a1fc3-000000@us-west-2.amazonses.com%3E][ACTION REQUIRED: Update FY19 Faculty Performance Evaluation and Goals]]
:LOGBOOK:
- Note taken on [2019-07-17 Wed 07:42] \\
  Called it 75% of these events
:END:
** CANCELED [#A]  Apparently I have to do something more here. [[message://%3c0101016bf736e1f5-a4c263f8-363d-43b6-9413-b58e8cd11e04-000000@us-west-2.amazonses.com%3E][Sentact | Deficiency # 5252 Unresolved 14 Days]]
:LOGBOOK:
- Note taken on [2019-07-17 Wed 07:01] \\
  Apparently this resolved itself because the issues aren't listed any more.
:END:
** CANCELED [#A] Sign and return contract
:LOGBOOK:
- State "CANCELED"   from "TODO"       [2019-07-25 Thu 08:04] \\
  Actually didn't have to do this.  This was just a copy of the contract for my records.  We did have to straighten out and error.
:END:
** DONE [#A] Complete this.  Due July 26. [[message://%3c269d583cc6d94f38897aad749ab031ca@RUPW-EXCHMAIL02.rush.edu%3E][Mandatory Identifying and Reporting Abuse LEAP Module Deadline]]
:LOGBOOK:
- State "DONE"       from "TODO"       [2019-07-23 Tue 09:22]
:END:

** DONE Completed conflic of interest statement.  No conflicts that I could think of.
:PROPERTIES:
:SYNCID:   B73BF4BA-41F0-4346-874D-87C48E641B9D
:ID:       E25DF361-403D-48BB-B73D-91C1D426EE7E
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2019-07-23 Tue 08:56]
:END:
* *Ticklers*
** DONE [#A] Get back to Bob on this.
SCHEDULED: <2019-07-08 Mon>
[2019-07-06 Sat 08:52]

[[message:%3C9cd7f2cda7184eb89571e30763fdb0ff@RUPW-EXCHMAIL02.rush.edu%3E]]
* *Notes*
** [[message://%3cb4a5a4971bdc4b1c9238295a8eaa1dba@RUPW-EXCHMAIL02.rush.edu%3E][Note on the move from Bill]]
  [2018-10-17 Wed]
** [[/Users/tshanno/Library/Mobile Documents/com~apple~CloudDocs/Excel/OMSP Phone list.xlsx]]
** [[/Users/tshanno/Library/Mobile Documents/com~apple~CloudDocs/Excel/OMSP Phone list 2019-02-25.xlsx][OMSP Phone List 2019-02-25]]
** [[file:///private/var/mobile/Library/Mobile%20Documents/com~apple~CloudDocs/Excel/OMSP%20Phone%20list.xlsx][OMIE phone list]] [2019-07-03 Wed]
** Safty issue tracking website [[message://%3c45A01C27-BF70-4128-BF58-8405397001FF@rush.edu%3E][Sentact Information]]

U:  tshannon
P:  calcium01

** [[message://%3c70f4cff3ccf44114b8f522a66651890b@RUPW-EXCHMAIL01.rush.edu%3E][OIME Team Building - volunteers needed]]


Hi all,
 
Thank you for taking the team-building survey!
 
We are excited to start putting some activities together for us to have fun and grow as a team!
 
Below are the top 5 activities that were selected and the people who have volunteered to take the lead.
 
We would like two people to co-lead each activity, so please email me if you are interested in co-leading any of these activities.
 
Top 5 Team-Building Activities:
Activity Leader(s):
Potluck
Mashonda Daniels
Sports outing
Katie Solka
Monthly lunch-hour yoga/dance class
Tamara Green
Volunteer event
Laney McDougal
Book club
Tessa Banks
 
Once we have all of the co-leaders, we will have a team-building committee meeting to schedule the activities and review/discuss the survey comments.
 
Thanks again for all of your input and enthusiasm!

** [[message://%3c70f4cff3ccf44114b8f522a66651890b@RUPW-EXCHMAIL01.rush.edu%3E][OIME Team Building - volunteers needed]]


Hi all,
 
Thank you for taking the team-building survey!
 
We are excited to start putting some activities together for us to have fun and grow as a team!
 
Below are the top 5 activities that were selected and the people who have volunteered to take the lead.
 
We would like two people to co-lead each activity, so please email me if you are interested in co-leading any of these activities.
 
Top 5 Team-Building Activities:
Activity Leader(s):
Potluck
Mashonda Daniels
Sports outing
Katie Solka
Monthly lunch-hour yoga/dance class
Tamara Green
Volunteer event
Laney McDougal
Book club
Tessa Banks
 
Once we have all of the co-leaders, we will have a team-building committee meeting to schedule the activities and review/discuss the survey comments.
 
Thanks again for all of your input and enthusiasm!

** [[message://%3c70f4cff3ccf44114b8f522a66651890b@RUPW-EXCHMAIL01.rush.edu%3E][OIME Team Building - volunteers needed]]


Hi all,
 
Thank you for taking the team-building survey!
 
We are excited to start putting some activities together for us to have fun and grow as a team!
 
Below are the top 5 activities that were selected and the people who have volunteered to take the lead.
 
We would like two people to co-lead each activity, so please email me if you are interested in co-leading any of these activities.
 
Top 5 Team-Building Activities:
Activity Leader(s):
Potluck
Mashonda Daniels
Sports outing
Katie Solka
Monthly lunch-hour yoga/dance class
Tamara Green
Volunteer event
Laney McDougal
Book club
Tessa Banks
 
Once we have all of the co-leaders, we will have a team-building committee meeting to schedule the activities and review/discuss the survey comments.
 
Thanks again for all of your input and enthusiasm!

** [[message://%3c07c42a10-41e1-42b7-941d-71b8de105d2f@rush.edu%3E][Promtions in RMC, Office of Integrated Medical Education]]
:PROPERTIES:
:SYNCID:   B009E480-9E15-4C5C-85F1-B0B3EA947686
:ID:       C0689966-62E7-433C-9049-65E57634FA7E
:END:


Greetings Everyone ,

I would like to share some exciting news in RMC, Office of Integrated Medical Education.

Jill Volk, director of admissions and recruitment has been promoted to Director of Diversity and Inclusion, Outreach and Recruitment for RMC, Office of Integrated Medical Education.  In this role Jill will combine her experience, expertise and strong leadership skills in working with UME and GME, to provide outreach, recruitment, retention and mentoring for students, house staff and fellows who are underrepresented in medicine (URM).  She will help foster and maintain a safe, inclusive and welcoming medical college climate for URMs.  Specifically, and in concert with the senior associate
 dean for D&I, Jill will also develop and implement a comprehensive diversity and inclusion
strategic plan.

Jill has a longstanding history of leadership and service at Rush that spans over two decades.
She began her career in the University where she served as director of student affairs managing office operations and the student activity budget, advising and developing student organizations, and providing career services opportunities to all university students.  Prior to her current role in RMC, Jill managed the RMC special programs/events, provided career counseling, advised first and second year students, served as the student liaison to the dean’s office, and RMC liaison to RU student services, financial affairs and the AOA chancellor.

Jill will continue in her role as director of admissions and recruitment, implementing the admissions and recruitment strategic plan and providing ongoing leadership and successful outcomes for increasing URMs in UME.  She brings a strong knowledge base of holistic review in admissions with successful URM recruitment and enrollment strategies.  Jill is active nationally with the Association of American Medical Colleges Group on Student Affairs (GSA) where she recently completed five years of service as Secretary and Treasurer for the GSA Central Region.  We look forward to her continued leadership and success in her new role.

Lolesia (“Lisa”) Johnson has been promoted to Project Manager for Diversity and Inclusion for RMC in the Office of Integrated Medical Education.   In her new role Lisa will serve as the primary point of contact for all key stakeholders to organize and manage the RMC D&I strategic plan and also serve as a liaison and strategic partner with department chairs, residency program directors, clerkship directors, the GME Diversity Equity and Inclusion Committee, Diversity Leadership Council and other key Rush university and medical college faculty, administrators and stakeholders to further advance RMC’s mission and URM diversity goals.   Lisa will work closely with the director and senior associate dean in creating innovative and new ideas that will further improve and promote diversity and inclusion excellence at Rush Medical College.

Lisa is a seasoned administrative professional with a wealth of past knowledge and administrative leadership that spans two decades in such areas/positions as RMC dean’s office, RMC admissions, physician office practice, research coordinator, and medical staff office operations.   Lisa has outstanding interpersonal, communication and problem solving skills that are well befitting her new role.   Lisa will start in her new position July 29th as she transitions out from her preclinical responsibilities.


Judith Busse’s role as Special Events Manager for UME has been expanded to also include GME.  While she will continue her responsibilities as events manager for UME, her role has further been expanded to support GME and the RMC D&I strategic plan in the Office of Integrated Medical Education. In this expanded role, Judith will collaborate on related graduate medical education (residents, fellows) events including Diversity Equity Inclusion Committee meetings and events, quarterly networking and social events for URM students, residents, fellows and faculty.  She will assist in the coordination and execution of social events to bring together prospective URMs, current underrepresented students, faculty and house staff through such events as Second Look Day, Interview Day, M1 Orientation, and other recruitment events/activities.  We look forward to Judith’s attention to detail and her indomitable and collaborative spirit in her expanded role.


These three individuals are dynamic leaders who will work in a collaborative and respectful manner with key stakeholders across the continuum of medical education to assure that RMC, Office of Integrated Medical Education is well aligned with the diversity and inclusion goals and vision of Rush University Medical Center.



Please join me in congratulating Jill, Lisa and Judith in their new roles.

pic 1.png                      RMC.png                 pic 3.png
** OIME Phone List 2019-08-09
  [[file:~/Library/Mobile%20Documents/com~apple~CloudDocs/Excel/OMSP%20Phone%20list%202019-08-09.xlsx][file:~/Library/Mobile Documents/com~apple~CloudDocs/Excel/OMSP Phone list 2019-08-09.xlsx]]

* DONE [#A] Review Grad School Material
	[[message://%3c6C327739-1022-4D25-867B-7BAA4FFD660A@rush.edu%3E][FW: Tom_Shannon@rush.edu]]
