* *Notes*
** [[~/Library/Mobile Documents/com~apple~Preview/Documents/Condo Vendor and Service List 2013.04.22 copy.pdf][Condo Vendor and Service List 2013.04.22 copy.pdf]]
* *Meetings*
** Bedbug inspection <2019-03-29 Fri>
** Plumber visited. <2019-05-28 Tue>
:PROPERTIES:
:SYNCID:   5DDB869C-F938-42A4-8F72-F0117BE17234
:ID:       AC6F0C8C-7DAA-4098-BBB1-53CB226A93CF
:END:

***** Removed garbage disposal.  I decided not to replace it.
***** Unclogged drain.
***** Will bill me later.  He said to sit down before I opened it but less than $1000.
  
  [[bbdb:Weinberg%20Plumbing][Weinberg Plumbing]]
**** He told me the garbage disposal was shot and not just because it was leaking.  I guess the bearings were bad.  He removed the broken garbage disposal and I told him to put in a simple drain in its place - I never used it anyway.

** RCN Repair
:PROPERTIES:
:SYNCID:   C60F1DBB-32DA-4861-BD92-7412D2C4DD39
:ID:       3C9EA44F-F3D1-486D-BED7-D0E8712C4F96
:END:
<2019-06-04 Tue 8:00-10:00>

Repair man came some time between 9 and 9:30.

He said that the signal was low but that wasn't the major problem.  They'll take care of that later because the problem  is outside the building.

Apparently the splitter was bad and the TiVO was broken.  He replaced the box.  I lost all of my recordings but no big deal.
** Air conditioner Repair <2019-07-16 Tue 09:00-12:00>
:PROPERTIES:
:SYNCID:   46D693AE-C721-4165-96F6-057FF787B127
:ID:       0A8D0970-1A1A-4CAD-B443-4568BBB32943
:END:
:LOGBOOK:
- Note taken on [2019-07-17 Wed 06:50] \\
  Someone forgot to put me on the schedule.  SO no one showed.  Rescheculed for tomorrow.
:END:
[[bbdb:Allstar%20Heating%20and%20Cooling][Allstar Heating and Cooling]]
* *Tasks*
** DONE Renew gym membership
[2019-06-21 Fri 02:43]

*** DONE [[https://profootballtalk.nbcsports.com/category/rumor-mill/][Rumor Mill – ProFootballTalk]]

#+BEGIN_EXPORT latex
\textbf{Curtis Crabtree} at \textit{profootballtalk.com} \href{https://profootballtalk.nbcsports.com/2019/06/21/pete-carroll-wide-open-competition-for-seahawks-backup-qb-job/}{addresses the Seahawks backup quarterback situation}:


\begin{quote}
``[[\textbf{Paxton}] \textbf{Lynch} is getting a second chance in Seattle after the former first round pick of the Denver Broncos flamed out after just two years with the team. [\textbf{Geno}] \textbf{Smith} is on his third new team in as many years after stops with the New York Giants and Los Angeles Chargers.

``'Paxton’s got a big time, live arm. He really does,' offensive coordinator \textbf{Brian Schottenehimer} said. 'For a big guy, he’s really quick and athletic, picked up the system well. Geno hasn’t been here nearly as long. He’s got a lot of moxie about him, great huddle command which is cool to see.'''
\end{quote}

I think we know who Smith is.  I'm not as sure about Lynch.

\href{https://predominantlyorange.com/2017/06/29/nfl-scout-says-paxton-lynch-miscast-gary-kubiaks-offense/}{Many have speculated that Lynch wasn't the best fit in the offense in Denver} and that may have been part of the reason he didn't develop.

So much of properly developing a quarterback has to do with pairing him with the right coaching staff.  You wonder how many of the busts over the last 30 years would have been stars had they been in the proper nurturing environment early on.

In any case Seattle is \textbf{Pete Carroll} is far more likely to adjust to Lynch's skill set.  Not that he's likely to get a chance to show it because quarterback \textbf{Russell Wilson} is a bit of an iron man but it will be interesting to see if Lynch does better there if he gets a chance to show it.
#+END_EXPORT
** DONE Renew gym membership
[2019-06-21 Fri 02:43]

** DONE [#A] Call to get air conditioner fixed
:PROPERTIES:
:SYNCID:   1F0D6C91-36C2-4FA2-8015-8350BEB224B3
:ID:       8C252455-33B7-4E6E-A303-BB054A07EC64
:END:
[[bbdb:Allstar%20Heating%20and%20Cooling][Allstar Heating and Cooling]]
** DONE [#A] Call to get air conditioner fixed
:PROPERTIES:
:SYNCID:   1F0D6C91-36C2-4FA2-8015-8350BEB224B3
:ID:       3AF4D914-3602-4594-B1D3-EF00CF7A556E
:END:
[[bbdb:Allstar%20Heating%20and%20Cooling][Allstar Heating and Cooling]]
