* How to cancel and view Apple subscriptions

Michael Potuck

Have you ever signed up for a first- or third-party subscription through Apple and forgotten about it? Whether you’d like to cancel one or just remember what services or apps you’re paying for, follow along…

It can definitely be convenient to subscribe to recurring services through your Apple ID, but it can also be easy to forget what you’re paying for and a bit tricky to view it all.

How to cancel and view Apple subscriptions

Option 1

Follow this link to see your subscriptions on iOS or Mac (credit to @rjonesy via @kylesethgray)
You’ll now see all the Active and Expired subscriptions tied to your Apple ID
Tap on one to cancel, change options, or see more information
Option 2

Open the App Store app on iPhone or iPad
Tap your profile icon in the top right corner
Tap on your name, then swipe down and tap on Subscriptions
You’ll now see all the Active and Expired subscriptions tied to your Apple ID
Tap on one to cancel, change options, or see more information


If you have multiple Apple IDs, don’t forget to check all of them.



You can also call Apple support to ask about any subscriptions you have associated with your Apple ID at 1-800-APL-CARE in the US. You can get more help at Apple’s support website as well.

