
* jags come out in zone  trying to play bend but dont break   hetting pressure will be important
* pats picking on Telvin Smith
* pats challenging jags w man to man defense  
* jags using play action against pats defense very effectively
* jags spreading the ball around well
* jags blocking well  Fundamentally sound  
* brady trying to feed gronk late in 2nd quarter  hes being doubled of course but still looks like he could catch the ball
* jags doing a good job of getting pressure on brady as of late in second quarter 
* jags really gave the pats a touchdown at the end of the first half with a series of stupid mistakes starting with ounting the ball instead of letting the clock rundown to the 2 minute warning and ending w a pass interference penalty inside the 10 yard line  
* bortles rallly having a great game.  cool and calm.  getting rid of the ball and generally preet accuarate
* brady supposedly hurt his hand last week.  i cant see any effects.
* not that many penalties but some were poorly timed
* terrible fumble by dion lewis early in fourth quarter with pats driving 10 pts down
* NE looks like they made some nice adjustments to stop the run at half.  Jags obviuosly thought they could wear them down.  It didnt work.
* teally should have noted earlier that pats lost gronk in the first hakf to the concussion orotocol
* for what happened inthe fourth quarter see the commment above abyt what happened at the half  
* 
