* Melissa Prusky
** Anxiety disorder
*** Pre-existing - since a college freshman
*** Why will this get better? "I appreciate that the stressors of medical school continue well beyond the preclinical years and thought it important to let you know that my psychiatrist and I don’t believe the enormous clinical and time demands of rotations will provoke anxiety for me in the way that rote visual memorization without a clinical framework has. I have years of clinical experience prior to medical school, and Dr. Jedel, my communications skills professor who observes all of my encounters with standardized patients, has told me on more than one occasion that my interpersonal and communication skills are 'outstanding.'"
** NOt a visual learner, memorization - anatomy
*** After VFG - a loto of tutoring (15 hours/week)
** East coast - brother lives here
** dad in a bad divorce
** pych. once a week or more
** Requests a leave of absence
** Has support from friends and family
** Took Health Euity but dropped it after VFG
** Questions
*** can she remediate just the blocks she failed (i.e. "deceleration")? Really a deceleration?
*** test anxiety?
*** academic counceling - she did that.xit

Entit
